### ISSUE TITLE
minor edit to __eq__ in class obspy.core.util.base.ComparingObjects

### ISSUE THREAD

**Issue by paitor** [obspy/obspy#1042]
Hi 

I wondering if it would be possible to edit the definition of the **eq** operator in class obspy.core.util.base.ComparingObjects from: 

```
def __eq__(self, other):
   return self.__dict__ == other.__dict__
```

to something along the lines (naively, there may be more intelligent ways):

```
def __eq__(self, other):
   try:
      return self.__dict__ == other.__dict__
   except:
      return False
```

The reason being that the current definition does not permit comparison to objects  that do not have the `__dict__` attribute, e.g. the comparison

```
obj == None
```

where obj is derived from  obspy.core.util.base.ComparingObjects

**Comment by krischer** [comment]
I don't see any harm in doing that; feel free to submit a PR or we'll eventually also get around to it. Its not a problem for `None` (see below), but for numbers and other builtins it might be a smallish problem if one is not careful.

As a side note: its good style to check identity and not equality for `None`, e.g. instead of

```python
obj == None
```

do 

```python
obj is None
```

**Comment by paitor** [comment]
Great, thanks for the pointer that'll be today's lesson for me 

Think I'll skip the PR (pull request?), as I don't know how to, and wait for the suggestion to magically find it's way in there. Meanwhile I'll skip the check in my code as it is not really vital for functionality

**Comment by trichter** [comment]
A similar check (for same class) was implemented at some point.
