### ISSUE TITLE
about obspy.signal.invsim

### ISSUE THREAD

**Issue by lileipku00** [obspy/obspy#1063]
In source code of obspy.signal.invsim, what is the purpose of "data[-1] = abs(data[-1]) + 0.0j"? Why doing this?

**Comment by krischer** [comment]
Link to the line of interest here:

https://github.com/obspy/obspy/blob/145269e8787ff5bbcf455c7fd6c1bbe8101565a3/obspy/signal/invsim.py#L597

Very good question and I don't know why that is done to be honest. The line is a bit peculiar so I assume there must be a reason for it.

It only modifies the spectrum at the nyquist frequency and it probably does not make any difference for actual data.

09802c889a68e3251015e04066e8012d10dd160d moves it from evalresp to invim. But in evalresp it used to only set the imaginary part of the number to zero so it changes a bit in this commit.

a51ca003513d6b3c63e900f766cce4ab90542431 originally introduced it.

@yannikbehr Do you remember why this is done?

**Comment by yannikbehr** [comment]
This ensures that the entry at the Nyquist frequency is purely real. I suspect, that it is possible that the frequency response coming from evalresp can have a very small imaginary value in which case it would make more sense to leave this line in evalresp. This would prevent potential problems in the subsequent deconvolution.  
@mbyt Do you remember anything about this?

**Comment by krischer** [comment]
I just looked it up and SAC does exactly the same as ObsPy does now: After the multiplication with the inverse response (any kind of response; not only evalresp) it sets the real part of the nyquist frequency to the absolute value of that frequency and the imaginary part to 0.0. It does not explain why unfortunately. Are we missing something obvious?

It also set the complex zero frequency to zero which we currently don't do. But we usually demean so that should not matter.
