### ISSUE TITLE
minor cleanup

### ISSUE THREAD

**Issue by petrrr** [obspy/obspy#1080]
Any need to keep this file around, and in particular to keep it in the distfile?
https://github.com/obspy/obspy/blob/master/obspy/lib/.gitignore

**Comment by QuLogic** [comment]
In the code, yes. It ensures that the `lib` directory exists when cloning.

In the distfile, probably not (if zips are okay with empty directories).

**Comment by megies** [comment]
This file is needed in order to have git keep the otherwise empty folder. Any need to get rid of the file? Did you check why it was added? From what I see it was added with a reason (ddca6e22a3b36dbef684) and to verify it's not necessary we would need to check the build (and more importantly packaging) process on all supported platforms (esp. Windows, since it's @barsch's commit) which is coming with quite some effort.

**Comment by petrrr** [comment]
Okay, I just though file https://github.com/obspy/obspy/blob/master/obspy/lib/__init__.py (which seems to have been added later) might be sufficient to ensure that the directory is kept around.

Anyway, couldn't we add a `global-exclude` rule, for any `.gitignore` file? 
But as mentioned in the title, its just a minor "cosmetic" change, so I will not insist.

**Comment by QuLogic** [comment]
Oh, you should have mentioned that earlier! We're too lazy to go look in the directory ourselves... :stuck_out_tongue: It's probably not necessary then.

**Comment by megies** [comment]
> We're too lazy to go look in the directory ourselves

Indeed, but doing so (now) reveals that it does contain an ignore rule for `*.so`, I'll move it to the root `.gitignore` and delete the file.

**Comment by petrrr** [comment]
@QuLogic: Well, I guess this `lazy issue` applied to me as well when filing this ticket. ;-) Anyway, I probably did not fully understand what the file was for originally. I just noted it being around where I did not expect it. So I did not document this ticket well. Apologies!

Thanks for taking care of this!
