### ISSUE TITLE
writing response files from traces/streams

### ISSUE THREAD

**Issue by EQDef** [obspy/obspy#1082]
Going through the documentation, I see that it is quite easy to get the response information using 'attach_response=True' in client.get_waveforms but I have no clue as to how I can write these.

I would like to write them directly with the stream is appears in several examples (including: http://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.remove_response.html).

Any help would be greatly appreciated!!

**Comment by megies** [comment]
After reading you normally do not get `tr.stats.response`, we just set this up for the example data from `read()` in order to easier illustrate some things.

For local (permanent) storage of waveforms and station metadata you should definitely store the original metadata (as dataless SEED or StationXML) along with your waveforms and attach them in your processing from these original metadata (most waveform formats do not have the capabilities to store the metadata along with the waveforms anyway).

Please go via the users mailing list with usage questions like this, you'll reach more people to answer there.

**Comment by EQDef** [comment]
Thanks for your input.  I very much appreciate all the work you all are doing on making Obspy, and making it better.

I agree that having a separate dataless would be useful, but I must say, I liked the idea of simply having a single file for simplicity (much as you have in your examples...).

To be more useful all around, I would suggest updating the examples to have them separately load the response info, or have a note clearly stating that this is not recommended.  I spent an unfortunate amount of time trying to figure out how to do that because of your example, without luck.

**Comment by krischer** [comment]
Shameless plug: http://seismicdata.github.io/pyasdf/

Maybe it helps but you still need to download both separately.
