### ISSUE TITLE
[FDSN client] parameter 'includeallmagnitudes' not properly detected

### ISSUE THREAD

**Issue by mherrmann3** [obspy/obspy#1094]
I wanted to access a FDSN server (http://arclink.ethz.ch) with the `includeallmagnitudes=True` parameter, but it returned 
> The parameter 'includeallmagnitudes' is not supported by the service.

However, the server supports it, e.g.: http://arclink.ethz.ch/fdsnws/event/1/query?eventid=smi:ch.ethz.sed/sc3a/2015ocwcdq&includearrivals=true&includeallmagnitudes=true#

Thanks for fixing!

**Comment by krischer** [comment]
The service has an an error in the `application.wadl` file: http://arclink.ethz.ch/fdsnws/event/1/application.wadl

It  is called `includemagnitudes` there which I guess its a typo. ObsPy uses that file to discover the capabilities of the server.

If you pass the faulty `includemagnitudes` to the service it will just be ignored. There is nothing we can do from our side. The service provider should:

1. Fix their `application.wadl` file.
2. Potentially raise an exception if an unknown parameter is passed as users will then not notice faulty requests.

Are you from the SED or should we let somebody else know about this issue?

**Comment by kaestli** [comment]
Ciao, thanks for pointing this out. I have fixed the wadl, and will take care that the fix is propagated back to the originator of the software.

**Comment by krischer** [comment]
Thanks!

I also think the server should respond with an error in case an unknown parameter is passed. Otherwise issues like this are really hard to nice.

http://arclink.ethz.ch/fdsnws/event/1/query?eventid=smi:ch.ethz.sed/sc3a/2015ocwcdq&includearrivals=true&bogusparameter=true

Table 1 in the spec states that error code 400 should be used for unrecognized parameters.
