### ISSUE TITLE
Internal mseed warning error, xseed.station Parser error

### ISSUE THREAD

**Issue by nlscelli** [obspy/obspy#1099]
Hi, 
have two different problems: 
1) while downloading huge amount of mseed files from FDSN clients sometimes i get this kind of errors:
/usr/lib/python2.7/dist-packages/obspy/mseed/core.py:356: InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=140, xn=142
  warnings.warn(msg, InternalMSEEDReadingWarning)
/usr/lib/python2.7/dist-packages/obspy/mseed/core.py:356: InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=219, xn=218
  warnings.warn(msg, InternalMSEEDReadingWarning)
/usr/lib/python2.7/dist-packages/obspy/mseed/core.py:356: InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=-298, xn=-299
  warnings.warn(msg, InternalMSEEDReadingWarning)
/usr/lib/python2.7/dist-packages/obspy/mseed/core.py:356: InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=-69, xn=-74
  warnings.warn(msg, InternalMSEEDReadingWarning)
/usr/lib/python2.7/dist-packages/obspy/mseed/core.py:356: InternalMSEEDReadingWarning: (null): Warning: Data integrity check for Steim-1 failed, last_data=146, xn=135
  warnings.warn(msg, InternalMSEEDReadingWarning)

The program keeps going, but as the program stucks at this point for a while this slows down the procedure. What does it actually mean? 

2) Whenever I have an xml file (both dowloaded from obspy clients or indipendently retrieved) that I want to parse to write the response with writeRESP i get this:
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-d4355b9ef9e8> in <module>()
----> 1 sp = Parser("bau")

/usr/lib/python2.7/dist-packages/obspy/xseed/parser.pyc in __init__(self, data, debug, strict, compact)
    105         # if a file name is given, read it directly to the parser object
    106         if data:
--> 107             self.read(data)
    108 
    109     def __str__(self):

/usr/lib/python2.7/dist-packages/obspy/core/util/decorator.pyc in new_func(*args, **kwargs)
    305                             except IOError:
    306                                 pass
--> 307             return func(*args, **kwargs)
    308 
    309         new_func.__name__ = func.__name__

/usr/lib/python2.7/dist-packages/obspy/xseed/parser.pyc in read(self, data)
    191         elif first_byte == b'<':
    192             # XML files should always starts with an '<'
--> 193             self._parseXSEED(data)
    194             self._format = 'XSEED'
    195         else:

/usr/lib/python2.7/dist-packages/obspy/xseed/parser.pyc in _parseXSEED(self, data)
    766         # blockette 10 and discard the rest.
    767         self.temp['volume'].append(
--> 768             self._parseXMLBlockette(headers[0].getchildren()[0], 'V',
    769                                     xseed_version))
    770         # Append all abbreviations.

IndexError: list index out of range

I would like to be able to perform writeRESP directly from the xml retrieved from obspy, but because of this I have to get dataless seed from an external source to be ablel to parse it.

**Comment by megies** [comment]
Please note the difference between the old XML-SEED format, which is a 1:1 representation of Dataless SEED, and the newly developed standard of StationXML.

The `obspy.xseed` Parser can handle Dataless (or Full) SEED or XML-SEED while the new Inventory class structure handles StationXML. Unfortunately we do not have an internal means to convert between the two formats, because this is a non-trivial task.

I suspect you are talking about StationXML files and the obspy.xseed Parser does not support those. So right now we do not have the possibility to write RESP files from StationXML in ObsPy.
You might want to have a look at [IRIS' java conversion tool SEED <--> StationXML](https://seiscode.iris.washington.edu/projects/stationxml-converter), you could convert from StationXML to dataless SEED and use that to write RESP files from within ObsPy.


The other issue, I can't say much about, it's what the messages tell you.. libmseed is encountering data inconsistencies during reading the data.
If you directly save the mseed data retrieved from the FDSN servers to file (`get_waveforms(..., filename="xxx"`) you avoid that ObsPy is reading the data, so that will be much faster (and you won't see those warnings).

**Comment by nlscelli** [comment]
Thank you very much, I was not knowing the difference between the two data files. About the mseed error issue, I would like to avoid the mseed direct download because I want to write them as SAC after some cutting and merging of traces.
