### ISSUE TITLE
Geographical locations for TauP

### ISSUE THREAD

**Issue by andreww** [obspy/obspy#1153]
I've recently been playing around with `obspy.taup` and found I needed to
know the latitude and longitude of points on a ray path or of the pierce 
points (e.g. for plotting CMB bounce points of PcP on a map). I ended up
producing a fairly simple subclass of `TauPyModel` with the addition of
an ellipsoid from `geographiclib` and have proof of concept code where
each point on a ray path has the latitude and longitude added. 

Is there any interest seeing this submitted to ObsPy? My current 
(not very pretty) code lives [here](https://github.com/andreww/cmb_summer_project/blob/master/tools/tomocorr/tomocorr2.py) but other APIs would clearly be possible. If this is something that would be interesting it would probably be a good idea to work out what the interface should look like first.

**Comment by krischer** [comment]
Hi Andrew,

this would be definitely be nice to have in ObsPy. Aside from the necessary geographic things and some tests this look like it could go straight in. It would be great if you could open a pull request.

The tricky thing here is to make sure the coordinate systems are correct - TauP works on a perfect sphere. But I think it is correct in your implementation (assuming that the arc length in `geographiclib` is defined in terms of an angle on the auxiliary sphere of the ellipsoid - which seems to be the case).

I propose to also add a `get_travel_times_geo()` method to have geographic variants of all the different methods. Also no need to subclass - just add it to the normal `TauPyModel`.

If porting the geographic functions turns out to be too difficult we could also make `geographiclib` a soft dependency and the geo methods will then only work if it is available.

Cheers!

Lion

**Comment by megies** [comment]
:+1:

**Comment by andreww** [comment]
#1164 is a pull request with this.

It's probably worth somebody reviewing and letting me know if there are style issues that need looking at. 

The tests at the moment are minimal and need to be expanded. In particular, it would be good to actually check the geographical location of pierce points and points on the path. But the only way I can think of to do this is to compare with the Java implementation. I played with this and discovered that paths have different numbers of points - which must be solvable.

Also, everything depends on `geographiclib`, to use `obspy/geodetics` we would need a  `calc_vincenty_direct` function (which I have laying around), and something to stand in for `Geodesic.Line` from `geographiclib` (which I don't have).

**Comment by megies** [comment]
Even has tests.. nice! (I'll leave the review to @krischer and @QuLogic who work with `obspy.taup` more)

Please do [this import of geographiclib](https://github.com/obspy/obspy/pull/1164/files#diff-49f591c57f67a64a8f67371a11d8a0a5R28) not in a general place but rather at the top (i.e. inside) of any of your new methods that need it (and raise an `ImportError` with friendly message mentioning that it's needed for this particular piece of functionality, see e.g. [here](https://github.com/obspy/obspy/blob/master/obspy/geodetics/base.py#L223-L233)). Like @krischer mentioned we handle `geographiclib` as a soft dependency so far (if it stays where you have it now, obspy breaks if it's not installed).
