### ISSUE TITLE
 error: unrecognized arguments:

### ISSUE THREAD

**Issue by Falcone78** [obspy/obspy#1161]
I use the obspy 0.10.2 in the Python 2.7.3 that is last stable version for Debian wheezy.
When import obspy in the python the system writes:
Namespace(seconds=None, t0=None, t1=None)
None None None
0:05:00
If rewrite "import obspy" the system the does not present the previous answer and works.
If put "import obspy" in a script .py the system don't works and produces the error:
[-h] [--t0 T0] [--t1 T1] [--seconds SECONDS]
check_xml.py: error: unrecognized arguments:
How it could be solved?

**Comment by krischer** [comment]
I think that is an issue with your python environment. Can you post a bit more details?

What happens if you type (on the shell):

* `python -c "import obspy"`
* `python -c "import lxml"`
* `python -c "import scipy"`

Also look at your `$PYTHONPATH` and `$PYTHONSTARTUP` env variables and this here: https://docs.python.org/2/tutorial/appendix.html#the-customization-modules

**Comment by Falcone78** [comment]
This is the result of my shell: 
# python -c "import scipy"
# python -c "import obspy"
Namespace(seconds=None, t0=None, t1=None)
None None None
0:05:00
# python -c "import lxml"
# echo $PYTHONSTARTUP

# echo $PYTHONPATH

**Comment by krischer** [comment]
Hmm...can you upload the output of

```bash
python -v -c "import obspy"
```

maybe to http://pastebin.com/ or something like it? Its too large to post it here.

**Comment by Falcone78** [comment]
http://pastebin.com/v5aKQna4

**Comment by krischer** [comment]
Can you try

```bash
python -v -c "import gettext"
```

And also produce the `script.py` file you mentioned earlier and run it with

```bash
python -v script.py
```

And upload the results again.

**Comment by Falcone78** [comment]
http://pastebin.com/cJxhxBQF

**Comment by krischer** [comment]
Hmm. I don't see the 

```
check_xml.py: error: unrecognized arguments:
```

line you mentioned in the first posty in there. Does the script work?

I'm at a bit of a loss here.


You could also try:

```bash
$ ipython
[1] pdb on
[2] run check.py
```

and diagnose the problem. Like where is the `check_xml.py` file located and who imports it??

**Comment by krischer** [comment]
the `pdb on` will cause python to enter debugger as soon as it encounters an error. You can then use `u` and `d` to jump up and down the call stack.

**Comment by Falcone78** [comment]
Meanwhile, I thank you for the effort and the help that you are giving me.
When I run the script.py, I add the time in this way: 
python -v script.py --now 2015-12-25T12:12:12
I have attached the result in the following link:
http://pastebin.com/pyz75uBJ
For the ipython I got the following error:
pdb on
Automatic pdb calling has been turned ON

In [2]: run check.py --now 2015-12-25T12:12:12
usage: check.py [-h] [--t0 T0] [--t1 T1] [--seconds SECONDS]
check.py: error: unrecognized arguments: --now 2015-12-25T12:12:12
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by krischer** [comment]
Oh I see...well I think you are just using your script wrong. It does not have a `--now` argument.

If that does not solve it, can you please upload the script somewhere?

**Comment by Falcone78** [comment]
https://drive.google.com/file/d/0Bx8mJ2JUhDMjNHcyU2loYWdrRG8/view?usp=sharing

**Comment by krischer** [comment]
The error is still a bit obscure to me - can you try to rename 
`/data/catalogo/DATA_XML/test.pyc` and `/data/catalogo/DATA_XML/test.py` to something not `test.*`? A file named `test.*` does not play well with some version of the `future` package.

I also don't know why most of your python packages are installed in `/usr/lib/python2.7/dist-packages`, whereas numpy is in `/root/.local/lib/python2.7/site-packages`. That could be a further source of error. 

Further things to try:
* run the `check.py` file in an empty directory.
* run `obspy-runtests` in an empty directory
* What is output of `python -c "import sys; print sys.path"`?

**Comment by QuLogic** [comment]
I'm sorry, but I do not believe there is any problem with ObsPy here. There are several compounding issues that are breaking things:
 * You are running as root. (OK, that's probably not a causal factor; it's just risky.)
 * There is an extra NumPy installation in `/root/.local` which may or may not be a problem.
 * Your script has too many bare `except`! If you did not wrap the `readEvents` in `try`/`except` (and why bother since it's going to `exit` anyway), you would see that the file downloaded is invalid because it's empty.
 * You are asking for `2015-12-25T12:12:12`, which is 2 months in the future. I know we use the future package, but it can't yet _predict_ the future.
