### ISSUE TITLE
Error when importing travelTimePlot

### ISSUE THREAD

**Issue by kensuke1984** [obspy/obspy#1167]
When I try to import travelTimeplot

by 
from obspy.taup.taup import travelTimePlot

I got error lines

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/obspy/taup/__init__.py", line 346, in <module>
    from .tau import TauPyModel  # NOQA
  File "/usr/local/lib/python3.5/site-packages/obspy/taup/tau.py", line 31, in <module>
    for i in range(12)]
  File "/usr/local/lib/python3.5/site-packages/obspy/taup/tau.py", line 31, in <listcomp>
    for i in range(12)]
TypeError: %x format: an integer is required, not numpy.float64
>>> 

What can I do?

**Comment by megies** [comment]
Looks like this is fixed in `master`: 1ca0a316d3ea9663e2a9d6f

Are you on Python 3.5? Just curious, because this commit is in #1121 which is supposedly about Python 3.5 compatibility..

The dirty but easy way is to just make [this change](https://github.com/obspy/obspy/commit/1ca0a316d3ea9663e2a9d6f6d5e2bb5a2f45fc04) to your `/usr/local/lib/python3.5/site-packages/obspy/taup/tau.py`

Or, wait for next release which should be out within a couple of weeks..

**Comment by kensuke1984** [comment]
Thank you for the comment.
I thought I mentioned about the version, sorry...

and yes exactly mine is 3.5 and IF I look the top page guide for installation... 3.4...


Thank you for your wonderful response. 
Sincerely

**Comment by megies** [comment]
The next release will also work with Python 3.5, anyway, closing.
