### ISSUE TITLE
st.fillter error

### ISSUE THREAD

**Issue by nghia1991ad** [obspy/obspy#1222]
I have a problem when doing the tutorial http://docs.obspy.org/tutorial/code_snippets/waveform_plotting_tutorial.html

st.filter("lowpass", freq=0.1, corners=2)

-->obspy.core.stream.Stream object at 0x7f352fdb1fd0

Can someone tell me what's wrong here? Thank you.

**Comment by megies** [comment]
Since you closed the issue, I assume you were able to reproduce the example. Please reopen if you have further trouble.

**Comment by nghia1991ad** [comment]
I still don't know what's wrong with the program but it runs well.

**Comment by megies** [comment]
If you're wondering about `obspy.core.stream.Stream object at 0x7f352fdb1fd0`.. the `filter` method returns the Stream object (in addition to changing it in place), which is useful for method chaining. I guess you're working in an interactive Python shell and then after execution of the line it shows the Stream object as the return value since it is not assigned to a variable.
