### ISSUE TITLE
docs.obspy.org site banner buttons unresponsive

### ISSUE THREAD

**Issue by calum-chamberlain** [obspy/obspy#1349]
Using Firefox v. 45 on Ubuntu 12.04, since release 1.0.0 the internal dropdown menu buttons in the docs.obspy.org banner (e.g. Documenation, Mailing Lists, Developer Resources) have been unresponsive - no dropdown or visible change in page.  

Not sure if this is something within obspy or the docs hosting.  I can replicate the issue using IE10, and Safari.

Curiously the dropdowns work on tests.obspy.org...

**Comment by barsch** [comment]
thanks for reporting!

@megies: URL not found for http://docs.obspy.org/_static/bootstrap-3.1.0/js/bootstrap.min.js - I temporarly rewrite the URL in nginx to /.../docs/stable/_static/bootstrap-3.3.4 - but this should be fixed directly in the doc builder script

**Comment by megies** [comment]
Uhm.. @barsch I'm probably the person that is least involved in the bootstrap theme in our docs. ;-)
I see some hardcoded bootstrap version numbers in the docs templates, but I think somebody who knows more about the setup should have a look.

**Comment by QuLogic** [comment]
The bootstrap 3.1.0 links comes from the local assets setting, which is true if running `make html`. The docs server should be running `make serverhtml` which uses stuff from CDN; was that changed or is it not passing along the local assets config properly?

(On a side note, I'm not sure why it's 3.1.0 since it really downloads 3.1.1...)

**Comment by QuLogic** [comment]
Or it could be the theme as you mentioned on gitter.

**Comment by megies** [comment]
Fixed, I think.
