### ISSUE TITLE
Nonlinloc to quakeml - picks are not associated with any channels

### ISSUE THREAD

**Issue by bvicic** [obspy/obspy#1587]
Dear all

When I am trying to convert nonlinloc file to quakeml event file, phases from nlloc are not associated with chans in quakeml file, although nlloc file does have them associated.

original issue:
https://github.com/eqcorrscan/EQcorrscan/issues/69

nlloc file:
https://drive.google.com/open?id=0BzMcKedS7yadaFRjZlFaYUpOQkU

I am using the script as simple as:
```
import glob
import os
from obspy import Catalog,read_events

cat = Catalog()

path = 'nllocs/'
event_files = glob.glob(path + '*.hyp')

for i, event_file1 in enumerate(event_files):

    cat += read_events(event_file1)
    print "Reading", i+1, "of", len(event_files)
    
    for event in cat:
    
        event.write("events/"+str(event.origins[0].time)+".xml", format="QUAKEML")
```
Is the channel association something that should be in quakeml format? the website https://quake.ethz.ch/quakeml/ is not working and I am unable to find this info.

Thanks,
blaz

**Comment by calum-chamberlain** [comment]
I don't think NonLinLoc files contain the full channel information (in your example it only gives the single-letter component name, e.g. Z, N or E).  I may be wrong in general, but when I have used NLL only the component has been there.

**Comment by blazvicic** [comment]
ok, thanks for clarification...this must be the problem then.

blaz

**Comment by megies** [comment]
I agree with @calum-chamberlain, in general there's only the component code in there (Z, N, E, ...) and not the full channel code. Although in the example file added by @claudiodsf I see full channel codes in the nlloc output hyp file. @claudiodsf how did you get a full channel code in there?

But then again, even if you had the full channel code in there, you're still lacking network and location code for proper association.. so, I think it's not really doable.

**Comment by d-chambers** [comment]
Closing since we aren't going to try to address this.

**Comment by megies** [comment]
Yep, I agree with closing this for now, although it's a real shame that NLLoc seems to not always make it possible to resolve the full SEED ID of used channels.

Still would be interested if @claudiodsf can shed more light on this though.

**Comment by megies** [comment]
Ah, interesting.. I actually left this field specifying the channel code empty always.. probably because nonlinloc has this in the docs (talking about single letter component codes) and the example has only `?` in there..:

```
[...]
        Component (char*4)
            component identification for the trace for which the time pick
            corresponds (i.e. Z, N, E, H)
[...]
        Example:

        GRX    ?    ?    ? P      U 19940217 2216   44.9200 GAU  2.00e-02 -1.00e+00 -1.00e+00 -1.00e+00
        GRX    ?    ?    ? S      ? 19940217 2216   48.6900 GAU  4.00e-02 -1.00e+00 -1.00e+00 -1.00e+00
        CAD    ?    ?    ? P      D 19940217 2216   46.3500 GAU  2.00e-02 -1.00e+00 -1.00e+00 -1.00e+00
        CAD    ?    ?    ? S      ? 19940217 2216   50.4000 GAU  4.00e-02 -1.00e+00 -1.00e+00 -1.00e+00
        BMT    ?    ?    ? P      U 19940217 2216   47.3500 GAU  2.00e-02 -1.00e+00 -1.00e+00 -1.00e+00

```

@alomax maybe the nonlinloc docs on http://alomax.free.fr/nlloc/soft6.00/formats.html#_phase_nlloc_ could be improved to use a proper SEED 3-letter component code in the example file and `Component (char*4)` specification..?

**Comment by megies** [comment]
Reopening this as we definitely should read the channel code unless it's just `?`.

**Comment by trichter** [comment]
I think I needed to address a similar issue when I wrote the plugin for SeismicHandler evt files. Only component information and the station code is specified in the evt files. I think the best option is to get the relevant infos from the Inventory object.

If someone is attacking this issue here, maybe he can reuse some code. Also it would be nice to have the same names for the relevant keywords. I used `inventory=None, id_map=None, id_default='.{}..{}' `, but this could also be changed, because it is not yet released.

Link to the file is [here](https://github.com/obspy/obspy/blob/master/obspy/io/sh/evt.py).
Extract from the file with documentation:

```
def _seed_id_map(inventory=None, id_map=None, id_default='.{}..{}'):
    if id_map is None:
        id_map = {}
    ret = id_map.copy()
    if inventory is not None:
        for net in inventory:
            for sta in net:
                if len(sta) == 0:
                    temp = id_map.get(sta.code, id_default)
                    temp = temp.split('.', 2)[-1]
                else:
                    cha = sta[0]
                    temp = cha.location_code + '.' + cha.code[:-1] + '{}'
                ret[sta.code] = net.code + '.{}.' + temp
    return ret


def _read_evt(filename, inventory=None, id_map=None, id_default='.{}..{}',
              encoding='utf-8'):
    """
    Read a SeismicHandler EVT file and returns an ObsPy Catalog object.

    .. warning::
        This function should NOT be called directly, it registers via the
        ObsPy :func:`~obspy.core.event.read_events` function, call this
        instead.

    :type filename: str
    :param filename: File or file-like object in text mode.
    :type inventory: :class:`~obspy.core.inventory.inventory.Inventory`
    :param inventory: Inventory used to retrieve network code, location code
        and channel code of stations (SEED id).
    :type id_map: dict
    :param id_map: If channel information was not found in inventory,
        it will be looked up in this dictionary
        (example: `id_map={'MOX': 'GR.{}..HH{}'`).
        The values must contain three dots and two `{}` which are
        substituted by station code and component.
    :type id_default: str
    :param id_default: Default SEED id expression.
        The value must contain three dots and two `{}` which are
        substituted by station code and component.
    :param str encoding: encoding used (default: utf-8)

    :rtype: :class:`~obspy.core.event.Catalog`
    :return: An ObsPy Catalog object.

    .. note::
        The following fields are supported by this function: %s.

        Compare with http://www.seismic-handler.org/wiki/ShmDocFileEvt
    """
    seed_map = _seed_id_map(inventory, id_map, id_default)
    ... and so on ... and later ...
            try:
                sta = p['station code']
            except KeyError:
                sta = ''
            try:
                comp = p['component']
            except KeyError:
                comp = ''
            try:
                wid = seed_map[sta]
            except KeyError:
                wid = id_default
            wid = WaveformStreamID(seed_string=wid.format(sta, comp))
            pick = Pick(waveform_id=wid, **_kw(p, 'pick'))    
```

**Comment by megies** [comment]
@trichter yeah something like this would be nice to be able to get fully correct association wherever necessary

**Comment by alomax** [comment]
Since the current NLL formats and source codes precede NetStaLocChan I see two options for accommodating NSLC:

1. Since the NLL station name (and phase) are used to find travel time tables for a pick, the current NLL station name (now char*64, since 2010) could be used a Net_Sta_Loc, as a given travel time table would correspond to NSL.  The Chan could be put in Component (now char*32), though this may break some things.  The "_" separated station name could be constructed when creating NLL input, and split/parsed when reading NLL output.  This solution works with NLL (since around 2010), and is a simple way to preserve the NLL association of picks with travel time tables though station name label, if NSL is used for travel time table construction.  This solution requires some organization and work on the user side.
2. A new NLL format is developed which explicitly contains NSLC fields.  This would require migration to new NLL code, may break some logic internal to NLL for organizing information, finding travel-time tables, determining magnitudes, etc.  In other words, time, money and bugs...

Current i/o fields:
 Station name (char*64) -     station name or code 
Instrument (char*32) -     instument identification for the trace for which the time pick corresponds (i.e. SP, BRB, VBB) 
Component (char*32) -     component identification for the trace for which the time pick corresponds (i.e. Z, N, E, H)

**Comment by megies** [comment]
Thanks for the info @alomax.

**Comment by megies** [comment]
Cahngeing this to a future major release since this would change behavior some..
