### ISSUE TITLE
"Not reported" as origin_type in quakeml

### ISSUE THREAD

**Issue by blazvicic** [obspy/obspy#1590]
Hello.

When reading quakeml files I sometimes get an error:

ValueError: Setting attribute "origin_type" failed. Value "not reported" could not be converted to type "Enum(["hypocenter", "centroid", "amplitude", "macroseismic", "rupture start", "rupture end"])"

which is easily solved by changing origin_type to something else from "not reported".
It would be nice if the reader would also accept "not reported".

blaz

**Comment by krischer** [comment]
Hi blaz,

this is just not a valid QuakeML file. If the origin type is not reported the `<type>` tag should not be present. `not reported` is not valid as an origin type (it would be valid as an event type).

The ObsPy reader does, to a large part, assume that the given QuakeML files are valid - otherwise all bets are off. It would of course be possible to work-around you particular issue but we would have to do this for essentially every tag and at this point it would no longer be recognizable as a QuakeML file.

You should report this to wherever you got the QuakeML file from and tell them to fix it.

Lion

**Comment by blazvicic** [comment]
thank you very much for clarification!

blaz
