### ISSUE TITLE
AttribDict does not have dict as a base class

### ISSUE THREAD

**Issue by megies** [obspy/obspy#1601]
Just noticed that..

```python
>>> d = AttribDict()
>>> isinstance(d, dict)
False
```

..which is quite unfortunate but I guess adding dict as a base class on AttribDict might be dangerous.. :-/

See #1598.

**Comment by krischer** [comment]
I think that's fine to be honest because its not a dictionary and we can probably find cases where it behaves differently.

Python 3 has abstract base classes for containers: https://docs.python.org/3/library/collections.abc.html

But these don't exist in Python and thus I'm not sure what we can do about it for now. There is probably a good reason why `AttribDict` does not inherit from `dict`.

**Comment by QuLogic** [comment]
> But these don't exist in Python

I assume you meant Python _2_ since you just stated they're in Python 3, but they [do exist there too](https://docs.python.org/2.7/library/collections.html#collections-abstract-base-classes).

**Comment by krischer** [comment]
Ah - that's good to know. Thanks!

**Comment by claudiodsf** [comment]
As I said here (https://github.com/obspy/obspy/pull/1598#issuecomment-262959149) both `AttribDict` and `Dict` inherit from `Mapping`. Don't know if that helps...

**Comment by megies** [comment]
Alright, so let's leave it as is. Just got surprised by this, I guess.
