### ISSUE TITLE
remove py3.3 from Travis CI

### ISSUE THREAD

**Issue by barsch** [obspy/obspy#1712]
or is there any reason for testing with it?

**Comment by krischer** [comment]
Would be okay with me. See also this discussion here. Its 9 month ago and almost nobody was using Python 3.3.

https://github.com/pypa/pip/issues/3796

Also official EOL of 3.3 is in 6 months.

On the other hand: do we have any 3.3 related hardships? If yes - remove it; if no: why not keep it if its no hassle?

**Comment by barsch** [comment]
the one and IMHO only argument against is reduced test time on travis - in ObsPy we officially support py3.3 anymore so we could remove it ...

**Comment by krischer** [comment]
@megies: Is there a deb package that still uses 3.3?

**Comment by megies** [comment]
[Ubuntu precise apparently has Python 3.2](http://packages.ubuntu.com/precise/python3), but [it goes end of live next month](https://wiki.ubuntu.com/Releases). Newer Ubuntu (that still have support) are Python 3.4 and upwards.

[Debian wheezy (current "oldstable") has Python 3.2](https://packages.debian.org/wheezy/python3) and [it has LTS until May 2018](https://wiki.debian.org/DebianReleases#Production_Releases). Debian Jessie (current "stable") is Python 3.4, upcoming Debian Stretch (current "testing", frozen already, release upcoming) is Python 3.5.

(It seems no supported Debian/Ubuntu has Python 3.3)

But: Since we have the deb buildbot CI, all of this doesn't concern too much whether we keep Travis tests enabled for Python 3.3.. But if we disable it we have a slightly strange situation because Py 3.2 and Py 3.4+ are tested and Py 3.3 not..
