### ISSUE TITLE
Can ObsPy add itself to the python 3 statement timeline

### ISSUE THREAD

**Issue by mnky9800n** [obspy/obspy#1764]
Can ObsPy add itself to the python 3 statement timeline?

http://www.python3statement.org/

This would be very helpful for users and developers of other projects.

**Comment by krischer** [comment]
We've discussed this a lot internally and also here: https://github.com/obspy/obspy/issues/1609

The bottom line is that we'll just be pragmatic and support Python 2 until it becomes too much of a hassle - its currently not that much additional effort as everything is already set up. Python 3 only will likely happen in any case once our core dependencies (numpy, scipy, matplotlib) do it. Also moving to Python 3 only is not that simple - see all the troubles the ipython devs had to solve to do it. I think there will just be a point in time when it will be natural for us to sunset Python 2 support.

I'm personally impartial to the Python 3 statement - I'm fine with being on it as long as we don't promise it before 2020. Other opinions?

**Comment by lijunzh** [comment]
> http://www.python3statement.org/
> 
> This would be very helpful for users and developers of other projects.

@mnky9800n Although I don't know the immediate value of signing that statement and add a timeline, I am fully in support to switch to py3. I personally use py3 exclusively for projects and only have py2.7 installed in virtualenv for testing purpose. Having to switch back and forth between py2 and py3 for collaboration with others really makes me annoyed. I am with you. 

> Many of them are not necessarily IT affine scientists and they all value backwards compatibility a lot - e.g. they don't want any of their scripts to break when updating ObsPy and they also don't really want to update their own installations ;-) I also believe that a large part of ObsPy's value comes from the fact that we very diligently test against fairly old dependency versions - this is for example important for observatories where infrastructure and OS updates only happen once in a blue moon.


Nevertheless, @krischer's statement in #1609 is very important here. Many researchers I know still use py2.7 and their code basis may break if an upgrade to py3 only happens. It is their responsibility to upgrade eventually (before 2020). But as a community that has large momentum and slow in adopting/upgrade to new tools, I see no rush of moving to a py3 only (that happens in my dream every once a while though). Go back to @markcwill's comment in @1609, it is very possible to have a py2 only version of Obspy (and many other packages) after 2020 since there will be definite needs for those to exist.

**Comment by jkmacc-LANL** [comment]
As a lazy scientist who just wants to filter and plot things (and play devil's advocate a little bit), all this Python 2 compatibility may be the only reason I still use it.  If things just work when I type `python do_something_seismic.py`, then Python 3 doesn't even really exist to me.  In the meantime, I'm still writing Python 2 code (for no particular reason) that _will_ break in the coming apocalypse.  Python 2 compatibility may be contributing to why the user base wouldn't cope well with a transition.  I'm actually in favor of threatening to sunset Python 2 support sooner rather than later, so that people see there's a cost in writing code that will break.  

Also selfishly, I think most of my contributor time has gone into compatibility issues, not features.  Writing compatible code isn't easy for me (I'm looking at you, `str`!), and it muddies my understanding of what the code I'm writing will actually do.  I don't have much time to contribute, and I'd rather spend it on new ideas.  I don't think Py2 compatibility is as big of a feature as an actual feature is.

**Comment by lijunzh** [comment]
> I'm actually in favor of threatening to sunset Python 2 support sooner rather than later, so that people see there's a cost in writing code that will break.

Great to hear this from a scientist. As an engineering, I tend to use the newest stable version of a software so that I can take advantage of the new features and improvements. Things change for a reason, and open software usually changes for good. However, most of the scientists I worked with try to stay with the old version that they are most familiar with. Maybe, it is because those old versions require them to do minimum work in code and free their mind for ideas. But as an engineer, this kind of practice makes me nervous. 

I like the threatening message approach. Now I see the benefit of signing that statement. Here is the logic behind it IMHO:

- For those like me who alway upgrade to newest version, they are probably forcing themselves to write py3 code by now;
- For those who are reluctant to upgrade but has no restrictions not to, this message gives them a reason;
- For some people that always stick to the oldest piece of software, they may not even upgrade Obspy to the latest version. So they are always safe and irrelevant to what we do in the new Obspy. 
- For people who want to upgrade but have a large code base in py2 that prevent them from doing so, they can either stay in the old version of Obspy. But this message gives them a clear warning not to write new code in py2 and consider picking on py3. 

In a word, we want to remind users that py3 is the future and we will inevitably move to it sometime by 2020.


> Also selfishly, I think most of my contributor time has gone into compatibility issues, not features.

I would second @jkmacc-LANL on that. Supporting for both py2 and py3 is the most frustration I had in working in Python environment. It forces us, as developers, to put too much energy in bridging the gaps while it can be easily avoided on the user side.

**Comment by krischer** [comment]
Good points!

We can definitely include the "threat" into the email that comes along with next ObsPy release.

I also share the sentiment about the additional compatibility burden and moving to Python 3 only would definitely ease that. Also Python 3.5 and 3.6 feel like the releases where there finally are tangible benefits over Python 2.7.

astropy seems to plan a new big release soon which they'll treat as an LTS release which will receive bugfixes until 2020. At the same time it will be their last release supporting Python 2. Seems like a reasonable way forward and we could think about doing something similar. We still probabably have to wait a bit until this path becomes more feasible as the tools are just starting to get ready to support this transitions (read this for some details: http://blog.jupyter.org/2017/04/19/release-of-ipython-6-0/).

**Comment by megies** [comment]
> I don't think Py2 compatibility is as big of a feature as an actual feature is.

That's all nice and sweet and in a perfect world we'd dropped Python 2 a long time ago and I know that keeping Py 2/3 compat can be a real hassle at times, but I would presume that a significant part of our user base would be hurting *a lot* if we suddenly drop Python 2 prematurely (i.e. before numpy, scipy, matplotlib and ultimately Python itself drop it).

**Comment by mnky9800n** [comment]
In 2010

> dropping python 2 prematurely

would be an adequate complaint. But in 2017?

Also, I, and no one else in the thread, have suggested dropping python 2 support. Only to advertise the availability of support for python 2 and python 3 in obspy so that users can migrate accordingly.

Also, per the link matplotlib has pledged to drop support by 2020 for python 2. So I could imagine that being an impetus according to your requirements.

**Comment by megies** [comment]
@mnky9800n well, if you read carefully, the above comments by @lijunzh and @jkmacc-LANL were clearly going in the direction of dropping Python 2 for ObsPy well before 2020.

"Prematurely" for me means before numpy/scipy drop it.

Sure enough, once one of our core dependencies (numpy, scipy, matplotlib, ..) drops Python 2, we'll surely drop it as well. Personally, I'd wait for a clear statement from numpy and scipy and then we can announce our own schedule.

**Comment by lijunzh** [comment]
> if you read carefully, the above comments by @lijunzh and @jkmacc-LANL were clearly going in the direction of dropping Python 2 for ObsPy well before 2020.

Let me clear myself a little bit here:

- Sentimentally, I want to move to py3 only **as soon as possible**. 
- Pragmatically, I understand the _restrictions_ on this switch and do respect the _challenges_ we are facing here.
- Regardless of this internal conflict, I still think a **warning** to users, informing them that py2 will be dropped some day and that day may come sooner than they might want, is something we need to start offering.  


The approach that I would propose for this switch is

- Prepare an *LTS version* that targets the py2 user base and promise update till 2020 and maintenance for a longer period (say two more years till 2022?)
- Start to work on **new features** for py3 only and offering py3 only release preview for those who are interested (I will be among those who try/test the prototype)
- These will prepare us when Numpy/Scipy makes the switch which is inevitable in the future IMHO. At that point, we can easily swap the main package from py2/py3 LTS to the py3 version.

In this way, we lower the bar for implementing new features, like @jkmacc-LANL  mentioned, and the developers will still work on maintenance and bug-fix for py2 through LTS. I understand this is a lot burden on the packaging team. @megies, @krischer, @QuLogic, maybe you guys can comment on that. But it may help the transition go smoother. Furthermore, young fellows coming out of college/universities are more likely to take the py3 path. It is unfair to let them go through the py2/3 twist like what we have experienced. I would dream of a perfect world that people only need to work with one Python and start to do practical work to make that happen.

**Comment by jkmacc-LANL** [comment]
I just think that saying "it'll be easier for users to move to Python 3 later" (when NumPy drops Py2 support) assumes that there will be less Python 2 code in 2020, and users are porting their code over right now.  That had better be true, or else it'll be *harder* for users to move code to Python 3 later.  In order to make sure users are currently porting their codes to Python 3, or just writing Python 3 exclusively, we'd better "threaten" them loudly and often, and maybe sign any pledge we can find:-)

**Comment by lijunzh** [comment]
> we'd better "threaten" (remind) them loudly and often

I totally agree with you. We should warn users over and over before actually doing anything to change the code so that they are perfectly aware of the situation. Maybe throw in some new features in py3 to lure them in, e.g. you can type `A @ B` in py3 instead of `np.dot(A, B)` for matrix multiplication.

**Comment by d-chambers** [comment]
>Sure enough, once one of our core dependencies (numpy, scipy, matplotlib, ..) drops Python 2, we'll surely drop it as well. Personally, I'd wait for a clear statement from numpy and scipy and then we can announce our own schedule.

I saw [this](https://github.com/numpy/numpy/blob/master/doc/neps/dropping-python2.7-proposal.rst) today. Numpy is no longer adding new features to python 2.7 starting in on Jan 1st 2019, and will completely drop support for python 2.7 on Jan 1st 2020. I guess obspy should do the same? 

> we'd better "threaten" (remind) them loudly and often

Maybe we should implement a big warning when importing obspy on python 2.7 in version 1.2.0 to start the long, persistent nagging? Also, I think we might be able to update some of the documentation to better encourage new users to start with python 3. 

> Maybe throw in some new features in py3 to lure them in

As far as the carrot approach is concerned, perhaps we  should encourage devs looking to release obspy related projects to consider python 3 only. It is a way to encourage obspy users to upgrade without directly impacting obspy itself. I hope to open-source a few small projects in the next few months that will be python 3 only.

**Comment by megies** [comment]
> Also, I think we might be able to update some of the documentation to better encourage new users to start with python 3.

That's a very good idea.

> should encourage devs looking to release obspy related projects to consider python 3 only

Yes, but I'm not sure how you would want to go after this.. Furthermore, updating proper projects is probably not the real problem, it's rather the tons of small user scripts not often used, or silently running in background somewhere that will hurt people most.

**Comment by krischer** [comment]
I'm all for adding a warning somewhere visible in the docs/website (not necessarily in the code) that people should really transition to Python 3 soon. We can also write it in the next release email to the mailing list.

> I saw this today. Numpy is no longer adding new features to python 2.7 starting in on Jan 1st 2019, and will completely drop support for python 2.7 on Jan 1st 2020. I guess obspy should do the same?

I also thought about this a lot and I'm personally not opposed to just use the same policy as numpy.

One personal comment: Currently the major compatibility hurdle we IMHO face in ObsPy is not py2/py3 as I think we figured this out but just very old numpy/scipy/requests/matplotlib versions that we still have to support as we want to support the default packages of the major linux distributions. I guess we could check how much easier this burden would be if we move to Python 3 only.

**Comment by megies** [comment]
> I guess we could check how much easier this burden would be if we move to Python 3 only.

Without checking.. I would assume  that most Linux distros will use the same or at least similar numpy version for both Py 2/3..

**Comment by megies** [comment]
> I'm all for adding a warning somewhere visible in the docs/website (not necessarily in the code) that people should really transition to Python 3 soon. We can also write it in the next release email to the mailing list.

👍

**Comment by d-chambers** [comment]
Added this as a check item in #2228, remember to close when that task is complete.

**Comment by megies** [comment]
This is kinda obsolete now
