### ISSUE TITLE
stream.write format error

### ISSUE THREAD

**Issue by s-harder** [obspy/obspy#1811]
I keep getting the following error. I'm trying to write 3 traces to a SEGY file.  Data are being converted from MSEED.

    stream.write(stream, "TEST.sgy", format="SEGY")
TypeError: write() got multiple values for argument 'format'

ObsPy version 3.6.1
Running on OSX Sierra, installed with Anaconda.

**Comment by lijunzh** [comment]
@s-harder First, you might be referring to the Python 3.6.1 instead of Obspy since we only have 1.0.3 released earlier this year. Secondly, it is not clear to me why you put `stream` as the first argument in your code here:


> ```
> stream.write(stream, "TEST.sgy", format="SEGY")
> ```

Since `write` is a method of `stream` class, there is no need to offer itself(stream) as an argument and may be the reason why you have `TypeError`

> `TypeError: write() got multiple values for argument 'format'`

Hopefully, this clears your doubts.

**Comment by s-harder** [comment]
You're right I'm referring to the Python version not the ObsPy version, which is 1.0.3.  However, if I remove the stream argument I get the following.  stream.write do not like my textual header.  My textual header is attached.
Thanks for your help.

    stream.write("TEST.sgy", format="SEGY", data_encoding=5, byteorder='>',textual_file_encoding='ASCII')
  File "/Applications/anaconda/envs/obspy/lib/python3.6/site-packages/obspy/core/stream.py", line 1444, in write
    write_format(self, filename, **kwargs)
  File "/Applications/anaconda/envs/obspy/lib/python3.6/site-packages/obspy/io/segy/core.py", line 435, in _write_segy
    segy_file.write(filename, data_encoding=data_encoding, endian=byteorder)
  File "/Applications/anaconda/envs/obspy/lib/python3.6/site-packages/obspy/io/segy/segy.py", line 232, in write
    self._write(file, data_encoding=data_encoding, endian=endian)
  File "/Applications/anaconda/envs/obspy/lib/python3.6/site-packages/obspy/io/segy/segy.py", line 243, in _write
    self._write_textual_header(file)
  File "/Applications/anaconda/envs/obspy/lib/python3.6/site-packages/obspy/io/segy/segy.py", line 287, in _write_textual_header
    textual_header = self.textual_file_header + b' ' * (3200 - length)
TypeError: must be str, not bytes

[header.txt](https://github.com/obspy/obspy/files/1062487/header.txt)

**Comment by lijunzh** [comment]
@s-harder Sorry for the late reply. I was caught up by something else.


> TypeError: must be str, not bytes

The error itself suggest that you might read the file `header.txt` in the byte mode instead of text mode. Recall that Python 3 distinguish string from bytes, which is different from what Python 2 does. In your code, did you use something like this to read the file

```Python
with open('header.txt', 'rb') as f:
    for line in f:
        #do something
```

Instead, try 
```Python
with open('header.txt', 'r') as f:
    for line in f:
        #do something
```

I am here only guessing your usage. If possible, could you please attach the entire code block that you used to write a stream?

**Comment by krischer** [comment]
@s-harder This is not really a bug but ObsPy was a bit strict and the error message was confusing. As @lijunzh pointed out the issue is due to the distinction of byte strings and textual (unicode) strings in Python 3.

```python
textual_header = self.textual_file_header + b' ' * (3200 - length)
```

will only work if `self.textual_file_header` is also a byte string. The error message complains that the right part, e.g. `b' ' * (3200 - length)` is not a text string if the left part is a text string - this is what you are seeing.

To fix it just encode your textual file header before setting it (or directly read it as a bytestring as proposed in the preceding answer):

```python
st.stats.textual_file_header = textual_file_header.encode()
```

#1813 contains a change so the next ObsPy version will do this automatically for you.

**Comment by lijunzh** [comment]
Thank @krischer for making this automatic. I really think people needs to pay more attention to the distinction between string and byte when they use py3 but making such transaction seamlessly will help people transition from py2 to py3.

**Comment by krischer** [comment]
I totally agree. There are also still a couple of places in ObsPy where this needs to be cleaned up because we initially only supported Python 2 and thus treated strings as bytes.

**Comment by lijunzh** [comment]
Yes. It is a difficult/troublesome change from py2 to py3 but very necessary IMHO. We will keep on discovering issues/bugs like this but eventually they will be cleaned up (at least at places where people actively use obspy). Any way, that was a quick fix of this issue. Great job!
