### ISSUE TITLE
SeisAn format <= 6 not properly detected, test data attached

### ISSUE THREAD

**Issue by chad-iris** [obspy/obspy#1864]
Even thought some code exists to detect SeisAn format 6 it is not properly detected under Python 3.6 (and likely others).  Detection via the internal _get_version() is fixed by adding the bytes literal declaration to the 'P' constant, i.e. `b'P'`, so 
https://github.com/obspy/obspy/blob/master/obspy/io/seisan/core.py#L102 should be:
```
if data[0:2] == b'KP' and data[82:83] == b'P':
```

But then it seams that this version of the format is not supported for reading.  I do not have time at the moment to investigate what it would take to add this support so I attach an example test file for someone else or a future me to use as a reference.

[2005-07-23-1452-04S.CER___030.gz](https://github.com/obspy/obspy/files/1258722/2005-07-23-1452-04S.CER___030.gz)

**Comment by megies** [comment]
> But then it seams that this version of the format is not supported for reading.

Seems like the [version is looked up](https://github.com/obspy/obspy/blob/5838487227913be0ab5e382a0fe115706928a576/obspy/io/seisan/core.py#L152) but it's not used at all during reading, I don't see any if/elses that make use of it.. so my guess is that the whole reading routine is tailored to one specific version.

**Comment by barsch** [comment]
its currently fixed to version 7 as I never got example files for other versions - however I'm already working on it

**Comment by barsch** [comment]
@chad-iris can you please convert the example file above to a mseed reference file in order to improve the test suite 

@chad-iris + @nikosT please feel free to attach seisan files in any other subformat (and if possible always combined with a reference file), such as 

version 7, 64 bit
version 6, 32 bit - not written with Microsoft Fortran (file starts with ```KP```)
also files written on different OS (Sun, Linux, MacOSX and PC) with the same data would be very usable ...

**Comment by chad-iris** [comment]
> @chad-iris can you please convert the example file above to a mseed reference file in order to improve the test suite (ofc not using obspy)

Reference file converted to miniSEED is attached.

[2005-07-23-1452-04M.CER___030.gz](https://github.com/obspy/obspy/files/1288675/2005-07-23-1452-04M.CER___030.gz)
