### ISSUE TITLE
UnsatisfiableError(conflict) in installing via conda (anaconda3-4.4.0 python3.6)

### ISSUE THREAD

**Issue by kensuke1984** [obspy/obspy#1868]
OS is CentOS 7. I use Zsh.
I installed the latest anaconda3-4.4.0 and followed the guide.
Python version is 3.6.2.  I installed the anaconda via pyenv.
I did update installed packages and also added the conda-forge channel.

Then I try ```conda install obspy``` and I got 'UnsatisfiableError: The following specifications were found to be in conflict:' as below

------------    
 UnsatisfiableError: The following specifications were found to be in conflict:
   - navigator-updater
   - obspy
   - python 3.6*
 Use "conda info <package>" to see the dependencies for each package.
-------------

**Comment by d-chambers** [comment]
hey @kensuke1984 you can either install obspy with pip or remove navigator-updater then install with conda.

**Comment by kensuke1984** [comment]
I could install by ```pip``` without deleting ```navigator-updater``` and its working!
Thank you very much. If there is a problem, I will inform again.

**Comment by megies** [comment]
> I could install by pip without deleting navigator-updater and its working!
> Thank you very much. If there is a problem, I will inform again.

I'd always try to use `pip` as a last resort when working in conda..

In any case it would be great if somebody could report this problem to Anaconda, because this really seems like a packaging problem with `navigator-updater`.

**Comment by megies** [comment]
Ah wait.. this is no packaging problem after all, the problem is that our obspy 1.0.3 packages are still on matplotlib 1.5.* which in turn depends on qt 4. On the other hand this navigator thingy depends on qt 5, so that's the problem..

See also https://github.com/conda-forge/obspy-feedstock/pull/13#issuecomment-326419698

So right now, you can't have obspy 1.0.3 conda package alongside this conda navigator. In any case, this will be resolved with obspy 1.1.0.
