### ISSUE TITLE
Using numpy.sum(st) for stacking: Misleading error message on incompatible Traces

### ISSUE THREAD

**Issue by Keowne** [obspy/obspy#1977]
Hi there,

This issue is using ObsPy 1.1.0, but I had the same trouble in 1.0.3. Installed via Anaconda Navigator, running on OSX 10.11.6. Python version is 3.6.2. [Without trying to confuse things, also occurs in ObsPy 1.0.2 installed via MacPorts, while using Python 2.7.13.]

Specifically, I am doing stacks of traces using e.g., stack = np.sum(st, axis=0). So long as all the traces have the same number of samples, this works fine. However, if the traces have different numbers of samples, there is an error regarding differing Trace IDs, which is not related to the actual problem whatsoever. Further, the two Trace IDs given in the error message, are always the top two of the list of traces in the stream, not necessarily those that have differing numbers of samples. This is highly confusing and frustrating to trouble-shoot.

The following code demonstrates this issue, by downloading 4 traces, 3 of which are 100 Hz (1080001 samples), and 1 of 50 Hz (540001 samples). Of the printed error messages at the end re. Trace IDs, the first set is before the stream is sorted alphabetically, and the second is after sorting alphabetically. In both cases, the error message, as stated earlier, regards the top two of the list of traces in the stream, not necessarily those that have differing numbers of samples. 

To reiterate, if the 50 Hz station wasn't there, there would be no error occurring. The fact that the stations have different IDs is immaterial.

Thanks!

```
import numpy as np
from obspy import UTCDateTime, read
from obspy.clients.earthworm import Client as Client_EW

client_ew = Client_EW("pubavo1.wr.usgs.gov", 16023)

t0 = UTCDateTime('2016-12-21T14:00:00.000000Z')
tdur = 3*3600

sta=['MSW','SSLN','DFR','ADAK']

st = read()
st.clear()

for i in range(0,len(sta)):
    print('Working on: ' + sta[i])
    st += client_ew.get_waveforms('AV', sta[i], '', 'BDF', t0, t0+tdur)

st.merge(fill_value=0)

print('\n')
print(st)

#Stream not alphabetical at this point
#AV.MSW..BDF  | 2016-12-21T14:00:00.008391Z - 2016-12-21T17:00:00.008391Z | 50.0 Hz, 540001 samples
#AV.ADAK..BDF | 2016-12-21T14:00:00.000000Z - 2016-12-21T17:00:00.000000Z | 100.0 Hz, 1080001 samples
#AV.DFR..BDF  | 2016-12-21T14:00:00.000000Z - 2016-12-21T17:00:00.000000Z | 100.0 Hz, 1080001 samples
#AV.SSLN..BDF | 2016-12-21T14:00:00.000000Z - 2016-12-21T17:00:00.000000Z | 100.0 Hz, 1080001 samples

try:
    stack = np.sum(st, axis=0)
except Exception as e:
    print(str(e))

#Prints: Trace ID differs: AV.MSW..BDF vs AV.ADAK..BDF

st.sort()

print('\n')
print(st)

#Stream now alphabetical
#AV.ADAK..BDF | 2016-12-21T14:00:00.000000Z - 2016-12-21T17:00:00.000000Z | 100.0 Hz, 1080001 samples
#AV.DFR..BDF  | 2016-12-21T14:00:00.000000Z - 2016-12-21T17:00:00.000000Z | 100.0 Hz, 1080001 samples
#AV.MSW..BDF  | 2016-12-21T14:00:00.008391Z - 2016-12-21T17:00:00.008391Z | 50.0 Hz, 540001 samples
#AV.SSLN..BDF | 2016-12-21T14:00:00.000000Z - 2016-12-21T17:00:00.000000Z | 100.0 Hz, 1080001 samples

try:
    stack = np.sum(st, axis=0)
except Exception as e:
    print(str(e))

#Prints: Trace ID differs: AV.ADAK..BDF vs AV.DFR..BDF
```

**Comment by megies** [comment]
While I agree that the error message shown is very confusing, I would argue that you should *a)* do the stacking differently and *b)* for such code should do several sanity checks on the input data yourself. It's even not trivial to uncover how your code ends up in the place this exception is raised in. Long story short: using `np.sum(st, axis=0)` there's just no real way to tell what might happen on the insides, which is never a good idea.

---

*a)* Debugging into your code, you see that due to the fact that numpy has no builtin AI that could try to make sense of just about any generic object it encounters, it falls back to the only way it considers safe to traverse the input data, which means that it iterates in loops over each individual trace, getting sample data by an incrementing index:

```
[3] > /home/megies/anaconda/envs/1.1.0py3/lib/python3.6/site-packages/obspy/core/trace.py(437)__getitem__()
-> def __getitem__(self, index):
(Pdb++) l
432  	            if self._always_contiguous:
433  	                value = np.require(value, requirements=['C_CONTIGUOUS'])
434  	            self.stats.npts = len(value)
435  	        return super(Trace, self).__setattr__(key, value)
436  	
437  ->	    def __getitem__(self, index):
438  	        """
439  	        __getitem__ method of Trace object.
440  	
441  	        :rtype: list
442  	        :return: List of data points
(Pdb++) n
[3] > /home/megies/anaconda/envs/1.1.0py3/lib/python3.6/site-packages/obspy/core/trace.py(444)__getitem__()
-> return self.data[index]
(Pdb++) self.data
array([ 24,  22,  22, ..., -26, -27, -28], dtype=int32)
(Pdb++) self.data[index]
22
```

This hardly seems like a good way to do the stacking, so you really should do this differently, which is a few lines of code instead of 1 but will be several orders of magnitude faster:

```
try:
    stack = st[0].data.copy()
except AttributeError:
    # handle no data at all here
    raise
for tr in st[1:]:
    # maybe add type checks for dtype of array, but should not be necessary, i think
    stack += tr.data
```

```
3 Trace(s) in Stream:
AV.ADAK..BDF | 2016-12-21T14:00:00.000000Z - 2016-12-21T14:08:20.000000Z | 100.0 Hz, 50001 samples
AV.DFR..BDF  | 2016-12-21T14:00:00.000000Z - 2016-12-21T14:08:20.000000Z | 100.0 Hz, 50001 samples
AV.SSLN..BDF | 2016-12-21T14:00:00.000000Z - 2016-12-21T14:08:20.000000Z | 100.0 Hz, 50001 samples

In [2]: def np_stack():
   ...:     stack = np.sum(st, axis=0)
   ...:     

In [3]: def obspy_stack():
   ...:     stack = st[0].data.copy()
   ...:     for tr in st[1:]:
   ...:         stack += tr.data
   ...:     

In [4]: %timeit np_stack()
193 ms ± 523 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [5]: %timeit obspy_stack()
50.5 µs ± 162 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

So, you see that having numpy guess how to perform stacking results in 4e3 times slower performance (this timing is for 500 seconds of data).

---

*b)* I would really strongly suggest to throw in a few sanity checks on input data before doing operations on the input data. If you run this code over loads of data,  it is only a matter of time when your code is doing illegal stacks. I think you should..
 - check that all traces have same length (alternatively you could even instead avoid the stacking with invalid zeros for gaps and leave out gaps in the stack, which would also mean having to adjusting the denominator of individual portions of the stack)
 - check that all traces really start at the same time (+- fraction of sampling interval)

**Comment by trichter** [comment]
What I think is happening is the following. Numpy is doing the summation internally using the `data` attribute of `Trace`. If this is not working due to different npts it is delegating the summation to Trace itself. Then the `__add__` method of Trace is called which has the id check as one of its sanity checks. IDs must be the same using `__add__`. I assume this is the case, because it is designed to merge data of the same station of different time ranges. I don't know how to improve this situation.

I always stack by something like `np.mean([tr.data for tr in stream], axis=0)`.

**Comment by Keowne** [comment]
Thank you very much for the detailed feedback and suggested stack method. It does prove very much faster and I will use this in future.

I should clarify that the code supplied in the original post was just to illustrate the problem. In practice, I do have what I'd thought were sufficient data and sanity checks to avoid this happening in the first place. 

While this is going off on a tangent from the original post, I had been finding the issue cropping up following use of the slice function where slice doesn't always produce traces of the same length sample-wise. This occurs if the specified start time used in slice, is earlier than that of the trace data being sliced. As there is no zero-padding built-in, sliced traces can have varying length, with no warning flag. One could argue again that slice shouldn't be used if there's a risk of this happening, and trim (which has zero padding) might be better.  The following example code demonstrates the issue:

```
#Code to demonstrate slice giving varying sample numbers 
#depending on if start time given to slice is earlier than start 
#of respective trace (with no warning flag given)

import numpy as np
from obspy import UTCDateTime, read
from obspy.clients.earthworm import Client as Client_EW

client_ew = Client_EW("pubavo1.wr.usgs.gov", 16023)

t0 = UTCDateTime('2016-12-21T00:29:00.000000Z')
tdur = 3.5*3600

sta=['SSLN','DFR','ADAK']

st = read()
st.clear()
for i in range(0,len(sta)):
    print('Working on: ' + sta[i])
    st += client_ew.get_waveforms('AV', sta[i], '', 'BDF', t0, t0+tdur)

st.merge(fill_value=0)
st.sort()
st.interpolate(sampling_rate=0.2,starttime=t0,time_shift=0)


arrivals = ['2016-12-21T00:28:31.876000Z',
            '2016-12-21T02:01:20.780000Z',
            '2016-12-21T01:14:25.427000Z']
slices = read()
slices.clear()
for i in range(0,len(st)):
    start = UTCDateTime(arrivals[i])
    slices.append(st[i].slice(start, start+3600, nearest_sample=True))

print('\n')

print(slices)

print('\n')

print("Arrival time relative to t0/data start (seconds)")
#-ve if arrival earlier than start time
#+ve if arrival later than start time
for i in range(0,len(slices)):
    print(slices[i].id + ": " + str(-(t0 - UTCDateTime(arrivals[i]))))

print('\n')

print("Slice start relative to t0/data start (seconds)")
#-ve if slice trace earlier than stream trace
#+ve if slice trace earlier than stream trace
for i in range(0,len(slices)):
    print(slices[i].id + ": " + str(-(t0 - slices[i].stats.starttime)))

#-OUTPUT----------------

#Working on: SSLN
#Working on: DFR
#Working on: ADAK

#3 Trace(s) in Stream:
#AV.ADAK..BDF | 2016-12-21T00:29:00.000000Z - 2016-12-21T01:28:30.000000Z | 0.2 Hz, 715 samples
#AV.DFR..BDF  | 2016-12-21T02:01:20.000000Z - 2016-12-21T03:01:20.000000Z | 0.2 Hz, 721 samples
#AV.SSLN..BDF | 2016-12-21T01:14:25.000000Z - 2016-12-21T02:14:25.000000Z | 0.2 Hz, 721 samples

#Arrival time relative to t0/data start (seconds)
#AV.ADAK..BDF: -28.124
#AV.DFR..BDF: 5540.78
#AV.SSLN..BDF: 2725.427

#Slice start relative to t0/data start (seconds)
#AV.ADAK..BDF: -0.0
#AV.DFR..BDF: 5540.0
#AV.SSLN..BDF: 2725.0

**Comment by krischer** [comment]
I don't fully understand the question. `.slice()` is exactly the same as `.trim()` except that it does not modify the original data but only offers a different view into it. Thus any in-place modification you make to a "sliced" trace would also show up in the original data. If we add zero padding to the slicing we would also have to modify the original data which would nullify the purpose of the `.slice()` method.

**Comment by Keowne** [comment]
It's just a comment suggesting that if one happens to specify a start time in the slice function that is actually before the data you're trying to slice should maybe flag a warning. Otherwise trying to track down the cause of the varying sample observation is a bit of a headache. Thanks.

**Comment by megies** [comment]
Just a thought.. maybe we could think about adding a well-behaved stacking method on `Stream` at some point, that also properly takes into account gaps. Probably somebody out there already has some reasonably good code for this already.

**Comment by krischer** [comment]
> It's just a comment suggesting that if one happens to specify a start time in the slice function that is actually before the start of the data you're trying to slice should maybe flag a warning. Otherwise trying to track down the cause of the varying sample observation is a bit of a headache. Thanks.

I'm not opposed to have an option that would either raise a warning or an exception in these cases. But it must be optional as we cannot change the current default behavior due to backwards compatibility concerns. Please open a separate issue to discuss this or send us a pull request with an implementation.



> Just a thought.. maybe we could think about adding a well-behaved stacking method on Stream at some point, that also properly takes into account gaps. Probably somebody out there already has some reasonably good code for this already.

I guess this might have some really tricky details but would of course be great to have :)

I'm closing this as the original question has been answered.
