### ISSUE TITLE
Evalresp doesn't recognise IRIS response units

### ISSUE THREAD

**Issue by calum-chamberlain** [obspy/obspy#2003]
Running the example [here](https://docs.obspy.org/tutorial/code_snippets/seismometer_correction_simulation.html#using-a-resp-file) raises an `EVALRESP ERROR` as follows:
```
 EVRESP ERROR (BFZ.NZ.10.HHZ [File: /tmp/obspy-2vae215y.tmp; Start date: 2009,323,01:00:01; Stage: 2]):
	check_units; units found ('COUNT - DIGITAL COUNTS') are not supported,
	skipping to next response now
```

This is running in a fairly clean anaconda env with obspy v. 1.1.0 - tested with both py3.5 and 3.6 (3.6 for the clean environment).  Digging deeper, it looks like it may be a change with the IRIS client - this worked yesterday, but not today, so I'm a little confused...?

If I replace `COUNT - Digital Counts` with `COUNTS` in the output file then there is no error. To me it looks like something changed at IRIS in how they write response units, but without a file from yesterday to hand it is hard to check.

**Comment by krischer** [comment]
I'm fairly certain this is a server side change from IRIS. Please not that this example is outdated in various ways and we should probably change it:

* The FDSN client can be used to get the response instead of the old iris client.
* `obspy.read_inventory()` can read RESP files and one can then just use the normal `remove_response()`. It think this should fix this particular error.

We cannot really do anything here as the example directly calls evalresp without using the ObsPy wrappers of `remove_response()`.

**Comment by FanXingli** [comment]
I encountered the same problem today. It seems that the st.simulate method can not process present RESP files from IRIS (COUNT - Digital Counts issue). After replacing the st.simulate lines of the outdated example with following lines, it works fine.

inv = read_inventory(respf, format='RESP')
st.remove_response(inventory=inv, output='DISP', pre_filt=pre_filt)

**Comment by krischer** [comment]
I fixed it in #2011. We don't really use this internally but it might help some people.

**Comment by krischer** [comment]
Magic issue closing does not appear to work anymore...

**Comment by QuLogic** [comment]
Issue closing only works when merging to `master`.

**Comment by krischer** [comment]
Good to know and makes sense I guess :)

**Comment by megies** [comment]
Yep.. this one would've been closed automatically on the next `maintenance_1.1.x`->`master` merge.
