### ISSUE TITLE
Write and/or Filter after Merge

### ISSUE THREAD

**Issue by jmsolanof** [obspy/obspy#2061]
Hi all,

I have to merge the traces I'm reading so the (enormous) amount of overlapping lines won't appear and more important I can filter data without the high pick on every overlap.

After some research I've found I have to fill the traces because of the masked values so I can filter traces and/or write files. Yet, it seems to me the filter is not working.

Also, the merge turns the long gaps (more than an hour) into a value of 1000000 so data becomes hard to visualize on plot.

Here is part of the code:
```
#After reading traces on st
st.merge(method=1)	# no more overlaps/gaps
for tr in st:                       # So the signal can be filtrated/saved
	tr.data = tr.data.filled()
st.filter('lowpass', freq=1.0, corners=2, zerophase=True) # filtering
```
These are not seismic signals but magnetic signals. They have a sinusoidal behavior with an offset.

My questions:
1. ¿Is there a way to filter them without the high peaks on every overlap/gap? (Which I think are related to the signal offset)
2. ¿Why is the filter not working after `merge()` and `tr.data.filled()`?

Thank you very much,

Juan Manuel

**Comment by krischer** [comment]
> ¿Is there a way to filter them without the high peaks on every overlap/gap? (Which I think are related to the signal offset)

Any filtering is tricky with gaps/overlaps because they result in strong jumps which maps into high frequencies and you will also encounter Gibb's phenomena when doing things in the frequency domain. Gaps/overlaps are always tricky (and and indication that something is wrong with the data) and there is no one right solution to deal with them so you might have to be very careful there. Also note that the `.merge()` method takes arguments so you can configure how gaps/overlaps are treated. Please have a look at the documentation.

One way to avoid at least a few issues is to process each continuous segment individually and carefully taper but I don't know if that is feasible for your application.


> ¿Why is the filter not working after merge() and tr.data.filled()?

`tr.data.filled()` calls the numpy `.filled()` method which will fill any masked values with the array defined fill value - this probably makes little sense.

**Comment by krischer** [comment]
Also please note that questions not related to code development are better suited for the mailing list.
