### ISSUE TITLE
SEG-Y Doc not correct

### ISSUE THREAD

**Issue by JesperDramsch** [obspy/obspy#2063]
The documentation for [obspy.io.segy.segy.iread_segy](http://docs.obspy.org/packages/autogen/obspy.io.segy.segy.iread_segy.html#obspy.io.segy.segy.iread_segy) states that `headonly = True` makes data unpacking on the fly available.

> headonly (bool)
> Determines whether or not the actual data records will be read and unpacked. Has a huge impact on memory usage. Data can be read and unpacked on-the-fly after reading the file. Defaults to False.

This seems incorrect. This seems to refer to #386 and #388. These are a little confusing due to trac2github, therefore I could determine the correct header without bugging @krischer directly (thanks again).

The correct headerword should be `unpack_headers` this should be reflected correctly in the docs.

**Comment by JesperDramsch** [comment]
Minimal code exemple:

`
in_name = 'tmp.segy'
for t in iread_segy(in_name,headonly=True,unpack_headers=False):
	tmp_slice = t.data
`

**Comment by ThomasLecocq** [comment]
I don't think it's wrong. The ``headonly`` is used by all reading routines and is only there to prevent data reading and unpacking, returning only the basic header information. For specific formats, like segy, you need to add ``unpack_headers`` to obtain the full ``segy`` header information.

**Comment by krischer** [comment]
![screen shot 2018-02-02 at 10 13 32](https://user-images.githubusercontent.com/800487/35725460-c029786e-0801-11e8-8628-033498be5b86.png)

The documentation is wrong. It claims that it can unpack the data on demand, similar to how the header values are handled in SEG-Y which is different than how `headonly` is handled for the other formats.

I think this would be really useful for SEG-Y because it allows filtering the traces before spending time unpacking the data so i'd rather fix the code than the doc.

**Comment by JesperDramsch** [comment]
Fixed the doc for now. Then the code can still be updated.

**Comment by JesperDramsch** [comment]
Headonly might also be interesting to keep. Then quick geometry calculations can be made.

**Comment by megies** [comment]
I guess this was covered by #2065? If not please reopen @JesperDramsch
