### ISSUE TITLE
Custom models built from .tvel

### ISSUE THREAD

**Issue by Phuripan2406** [obspy/obspy#2192]
I'm trying to create a custom model for the moon. In my .tvel file, the format is shown below:

NAME         nonlayered_1D
UNITS        m
depth vp vs rho
0	2637	1522	2217
1	3037	1753	2297
2	3382	1953	2360
3	3695	2133	2412
4	3987	2302	2459
5	4209	2430	2492
6	4422	2553	2523
7	4561	2633	2543
.
.
.
1125	7308	4219	2861
1126	7308	4219	2861
1127	7308	4219	2861
1128	7308	4219	2861
1129	7309	4220	2861
1130	7308	4220	2861
1131	7308	4219	2861
1132	7308	4219	2861
1133	7308	4219	2861

when I ran, this command 'obspy.taup.taup_create.build_taup_model('/import/deadlock-data/pjangthongsiri/Works/nonlayered_1D.tvel', output_folder='import/deadlock-data/pjangthongsiri/Works', verbose=True)', I got this error: IndexError: index -1 is out of bounds for axis 0 with size 0.

I tried to change the columns from vp vs rho to vs vp rho, I got an error that 'S velocity is greater than P velocity'. I don't know what I did wrong. Please help.

Sincerely,
Glory

**Comment by krischer** [comment]
Hi Glory,

`depth vp vs rho` is the right order. I'm actually not entirely sure how TauP behaves without  any layers. Also can you upload the full model somewhere? Otherwise it will be hard to reproduce this.

I'm not sure if anyone ever used our taup implementation for Moon calculations so who knows what works and what does not. So you will probably have to become a bit active yourself if you want this to be resolved fairly quickly.

I would start with a simpler model. For example you could start with this model (https://github.com/obspy/obspy/blob/master/obspy/taup/data/iasp91.tvel) and scale all radii until they match the moon. If that works start modifying velocities. And one point it will start to break down and we know better where to look.

**Comment by megies** [comment]
Closing this on the assumption that it's likely now fixed in master
