### ISSUE TITLE
Catalog to NLLOC_OBS: picks without time_error

### ISSUE THREAD

**Issue by claudiodsf** [obspy/obspy#2371]
When converting a `Catalog` object to `NLLOC_OBS`, phase picks without a time error are given an error of `-1` (see [here](https://github.com/obspy/obspy/blob/master/obspy/io/nlloc/core.py#L409)). 

I did some check, and I think that NonLinLoc interprets the time error always as positive, which gives a time error of one second! (pinging @alomax to be sure of that).

So, I think that the time error should be set to zero in these cases.

**Comment by alomax** [comment]
Correct.  The time error is always squared on use, so a value of -1 will be used as 1sec.
If no pick uncertainty is available, then 0.0 should be used. But it is undesirable not to have pick uncertainties in NLL, as the probabilistic location search relies on pick and travel-time uncertainties for weighting the misfit function.  If pick uncertainty is 0.0, then the travel-time uncertainties have to be finite and carefully set (LOCGAU or LOCGAU2).
The pick uncertainty can also be specified with type QUAL <int> instead of GAU <float>, in which case a LOCQUAL2ERR statement in the NLLoc control file sets the time uncertainty based on the <int> value.  So when a pick uncertainty is not available, setting QUAL 0, for example, would allow assigning a pick uncertainty at NLLoc run time.  But this would break at NLLoc runtime if a LOCQUAL2ERR statement is not used...

**Comment by megies** [comment]
Ok, @claudiodsf so I guess we can only set it to `0.0` if we have no info then? If that'd be the case @LMurrayBergquist can make the change..

**Comment by claudiodsf** [comment]
So, if I understood correctly, a NLLOC_OBS line can be something like:
```
UH1    ?    ?    ? P      ? 20100527 1656 26.1300 QUAL 0 -1.00e+00 -1.00e+00 -1.00e+00
```
This would force the user to take action and define what a `QUAL 0` pick means in NonLinLoc.

Isn't that a better option?

**Comment by alomax** [comment]
The QUAL system follows the old hypo* location code 0-4 or 0-N weighting system.  So QUAL 0 would be the best quality / smallest uncertainty pick.  But if only QUAL 0 is present, then, yes, this forces a definition of the uncertainty.  Currently, NLLoc will probably crash if there is no LOCQUAL2ERR statement and QUAL is used, so not a very elegant solution...

**Comment by claudiodsf** [comment]
So, from your perspective, it is better to put `GAU 0.0`? (We need to put something, anyway)

**Comment by alomax** [comment]
That is probably the safest compromise. Hopefully most pick readings moving through QuakeML and ObsPy will have uncertainties...

**Comment by claudiodsf** [comment]
👍 So will @LMurrayBergquist make the change? (otherwise I can do it 😉 )

**Comment by LMurrayBergquist** [comment]
Sure! If you haven't changed it, I can do that now.
