### ISSUE TITLE
PPSD.add¶

### ISSUE THREAD

**Issue by atilapaes** [obspy/obspy#2386]
Hello guys,

obspy.signal.spectral_estimation.PPSD.add was not working with a data sample I was trying to input.
Then I found info in a forum saying the sample must have at least one hour of continuous record. Please add this info to the documentation. 

Cheers.

**Comment by krischer** [comment]
The `ppsd_length` argument of `PPSD.__init__()` allows you to steer the length of data passed to the actual psd. I guess we could raise a more appropriate warning somewhere?

@atilapaes Please feel free to submit a PR with an updated documentation or a better warning message that would have helped you diagnose the problem quicker.

**Comment by JoshRichW** [comment]
Sorry to jump in on such an old issue, but I ran into this problem in my own code.
After a bit of tracking it down, the `PPSD.add` function will fail silently because there is no failure catch in the while loop on line 881 of signal.spectral_estimation, specifically:
 
`
while t1 + self.ppsd_length - tr.stats.delta <= t2:
`

If the while statement never evaluates True then no warning is raised but the information is not added to the ppsd - a silent failure.

One option for a fix could be to add:
```
if t1 + self.ppsd_length - tr.stats.delta > t2:
        msg = ("Trace was shorter than ppsd length. Skipping:\n" +
                   str(tr))
        warnings.warn(msg)
        continue
```
just before the while statement. 
This if statement will only trigger if the initial trace is shorter than the expected window, and then we skip the trace to avoid running the while loop and effectively evaluating the same condition twice.
