### ISSUE TITLE
Update to FDSN StationXML 1.1

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2421]
We need to update to StationXML 1.1: see https://github.com/FDSN/StationXML/releases/tag/v1.1

**Comment by aringler-usgs** [comment]
@megies Just an FYI: IRIS is still using v1.0: E.g. [ANMO](http://service.iris.edu/fdsnws/station/1/query?net=IU&sta=ANMO&loc=10&cha=BHZ&starttime=2019-06-07T20:00:00&endtime=2599-12-31T23:59:59&level=response&format=xml&nodata=404)

**Comment by megies** [comment]
Interesting, thanks @aringler-usgs

**Comment by chad-iris** [comment]
For what it's worth, the DMC is soon going to be shipping StationXML 1.1.  Hopefully the UserWarning for this state of mismatch isn't too noisy:
```
.../obspy/io/stationxml/core.py:84: UserWarning: The StationXML file has version 1.1, ObsPy can deal with version 1.0. Proceed with caution.
  root.attrib["schemaVersion"], SCHEMA_VERSION))
```

Note that StationXML is intended to be backwards compatible in major versions, meaning that one should always be able to parse 1.0-expected data from a 1.x documents.  The removal of "storage format" in StationXML 1.1 is an extremely rare exception, that I do not expect to be repeated.

**Comment by mikehagerty** [comment]
Hi Chad,
so for stationXML 1.1, do you still recommend:
<InstrumentSensitivity>
   <Polynomial>
             <ApproximationType>MACLAURIN</ApproximationType>
             <FrequencyLowerBound unit="HERTZ">0.0</FrequencyLowerBound>
             <FrequencyUpperBound unit="HERTZ">0.5</FrequencyUpperBound>
           ...
or is it now:
<**InstrumentPolynomial**>          // replaces <InstrumentSensitivity> for polynomial response (?)
 <Polynomial>
 
And for Tobias/Lion,
Is there an equivalent to InstrumentPolynomial in obspy yet ?
e.g., so that converting obspy to stationXML will generate this block ?

Thanks!

**Comment by megies** [comment]
@chad-iris you happen to have some example files for testing with 1.1 at hand?

**Comment by mikehagerty** [comment]
Hey Chad,
I just did a test to replicate the blockette 062 example presented in the section on polynomial responses in the SEED manual (V2.4 2012):
    client = Client("IRIS")
    starttime = UTCDateTime("2004-10-01")
    endtime = UTCDateTime("2004-10-02")
    inventory = client.get_stations(network="BK", station="CMB", channel="LKS",    
                                    starttime=starttime, endtime=endtime, level="response")

If I step through the stages of the resulting response, I can see:
stage 1 = raw Maclaurin polynomial response stage
stage 2 = digitizer A/D
stage 3 - 8 = Decimation

When I write this out as xml using inventory.write(), it will not validate (since that
stage is missing a gain <value>), but if I do:
   inventory.write(..., validate=False)
it writes what looks like correct v1.1 stationXML polynomial response
>        <Response>
          <InstrumentPolynomial>
              ...
             <ApproximationType>MACLAURIN</ApproximationType>
              ...
          </InstrumentPolynomial>
          <Stage number="1">
             <Polynomial>
                 ...
              </Polynomial>


i.e., it correctly puts the raw Maclaurin coefficients in a stage=1 polynomial block,
and precededes this by a "InstrumentPolynomial" block that contains the correctly
scaled Maclaurin coefficients.

So it's doing it correctly wrt stationXML 1.1 (near as I can tell), but it's trying to validate
it against the old schema as expected.

So my next step is to see if I form my own stage 1 polynomial response + datalogger, if it correctly produces the InstrumentPolynomial block.

Cheers!
-Mike

**Comment by mikehagerty** [comment]
Actually Chad,
I think the way the example above works is that IRIS is returning a
stationXML that already contains the InstrumentPolynomial
block (with properly scaled coefficients), before all the stages.

Can you confirm this ?  Is this how it's stored at IRIS or are you guys
converting from Dataless seed on the fly ?

Thanks!

**Comment by mikehagerty** [comment]
Hi Tobias,
So, I'm working on a project that needs to convert from response files in
yaml to obspy to stationXML.
I don't think you want to deal with yaml files :)

It might be easier just to look at the code snippet I posted on the thread,
that uses the IRIS client
to retrieve a known polynomial response.
To me it looks like everything is working the way it should: obspy is
scanning a InstrumentPolynomial object
from the return IRIS xml response, and attaching this ahead of the response
stages (including the stage 1 = PolynomialResponseStage).
The resulting inventory.write produces valid (I think) stationXML 1.1
output for polynomial response.

So I think the issues are:
1. can't validate the resulting stationXML against the 1.0 schema, needs
the 1.1 schema
2. You have a catch in core/inventory/response.py to not try to calculate
the frequency response
     def _call_eval_resp_for_frequencies(..)

1230             elif isinstance(blockette, PolynomialResponseStage):
1231                 msg = ("PolynomialResponseStage not yet implemented. "
1232                        "Please contact the developers.")

And I think this is correct since you can't do it for
PolynomialResponseStage.
I just flagged it because it looks like the code handling polynomial
response may change after the switch
to schema 1.1

Cheers,
-Mike

**Comment by claudiodsf** [comment]
Hi, for information, RESIF just moved to StationXML 1.1.

Example:

https://ws.resif.fr/fdsnws/station/1/query?network=G&station=ECH&level=station&format=xml&nodata=404

**Comment by megies** [comment]
I am tempted to bump this to 2.0.0 in order to finally get 1.2.0 out. It looks like we can still read 1.1 documents, even if additional info will not be parsed.

Of course, if anybody volunteers to commit to handling this within the next few days, that's a different matter then obviously, and very welcome.

**Comment by megies** [comment]
List of changes here: https://github.com/FDSN/StationXML/blob/master/Changes.md

**Comment by megies** [comment]
Bumping to 2.0

**Comment by mikehagerty** [comment]
Hi Tobias,
Do you mean that you're pushing this issue to obspy release 2.0 (?)

To clarify: it looks like a one-line code to change the schema version in
./io/stationxml/core.py:def validate_stationxml(..)

but the bigger issue is in generating stationxml from obspy inventory
objects that
conforms to the new (1.1) fdsn version (?)
(e.g., a polynomial response can't have an instrument_sensitivity, etc)

I can try to look at this after AGU.

Cheers,
-Mike

**Comment by nick-iris** [comment]
I'm going to take a stab at addressing the list of changes at https://github.com/FDSN/StationXML/blob/master/Changes.md in the next few hours. Would be really good to have StationXML version 1.1 supported in the next release.

**Comment by nick-iris** [comment]
I started working on this in PR https://github.com/obspy/obspy/pull/2510 . There's not too much left if we want to make a push to have this included in the next release. Otherwise I'm afraid users will soon be bombarded with StationXML version warnings, as @chad-iris mentioned, since the FDSN has approved version 1.1. 

The RESIF datacenter is already shipping version 1.1 from there implementation of the fdsnws-station service, and the IRIS web services will soon be as well.

**Comment by megies** [comment]
I'm all in for having this in 1.2.0. My only concern is that we have to be *really* careful with changes in the Inventory objects, so that we don't break anything when reading StationXML 1.0.

**Comment by mikehagerty** [comment]
In a related issue: I've been using the NRL client to form inventory
objects to write out as stationxml for
validating against the schema and also against the iris rules/units (I'm
not even sure if/how these are
going to be made official/mandatory).

Anyhow, I notice that:
The NRL client is automatically inserting a stage=2 pre-amp placeholder
between the sensor (stage 1) and the
    digitizer (stage 3+).  It correctly has stage_gain=1.0 and
input/output_units='V'
However, if I do inventory.write() on the resulting inventory object, it
*drops* the input/output_units on stage 1

I'm not sure if this placeholder stage is supposed to be there (though it
shouldn't affect the response),
but dropping the input/output_units definitely violates the iris rules:
https://github.com/iris-edu/stationxml-validator/wiki/Validation-tests
e.g., 403 Stage[N]:InputUnits:Name must equal Stage[N-1]:OutputUnits:Name.

Cheers,
-Mike

**Comment by megies** [comment]
@mikehagerty this is kinda off topic here, so I'd rather have follow ups goin into another ticket. In any case, I'm not saying there shouldn't be improvements to what our NRL client outputs, but FDSN defines the standard, so that's what we validate against.
Personally, I also don't like some aspects like how stations can completely lack coordinate info and stuff, but hey.. it's allowed by the standard.

**Comment by nick-iris** [comment]
@megies  I just noticed that you made a bunch of improvements. Do you want me to continue working on this, or would you rather take it over yourself?

**Comment by megies** [comment]
@nick-iris see https://github.com/obspy/obspy/pull/2510#issuecomment-571967735
