### ISSUE TITLE
obspy.taup.tau.Arrivals.plot_rays: color of ray paths 

### ISSUE THREAD

**Issue by okling** [obspy/obspy#2470]
ObsPy version: 1.1.0
Python version: 3.6
Platform: OsX and Anaconda

Hi, 

I'm plotting 3 phases ["PcPPcPPKP", "PcPPKPPcP", "PKPPcPPcP"], which have similar ray path, using obspy.taup.tau.Arrivals.plot_rays. Since they are all plotted in the same color, it's difficult to distinguish them. However, there is no option in that function to change the color of the ray paths. Is there a way to do that?

![Raypath_cKK](https://user-images.githubusercontent.com/32896474/66133769-85717980-e5f7-11e9-94d1-b184e3af2cb0.png)

Thank you in advance.

**Comment by QuLogic** [comment]
Please provide the code you are using like it asks in the template.

**Comment by okling** [comment]
I'm sorry that I forgot to attach the code.

```
import math
import matplotlib.pyplot as plt
from obspy.taup import TauPyModel
from obspy.geodetics.base import gps2dist_azimuth  
from obspy.geodetics import kilometers2degrees 

def plot_phasepath(model, lat_event, lon_event, dep_event, lat_sta, lon_sta, phases, arrival=False, plot=False):
    model_ev = TauPyModel(model=model)
    dist, azi, bazi = gps2dist_azimuth(lat_event, lon_event, lat_sta, lon_sta)
    dist_deg        = kilometers2degrees(dist/1000.)

    arr_path = model_ev.get_ray_paths(source_depth_in_km=dep_event, distance_in_degree=dist_deg, phase_list=phases)

    if arrival:
        print(dist_deg)
        print(arr_path)

    arr_path.plot_rays()
    plt.legend(loc="center", bbox_to_anchor=(1.0, 0.045),fontsize="xx-large")
    if plot:
        plt.savefig('Raypath.png', dpi=180)

# Background model
model = "iasp91" 

# Event parameter
lat_event = 51.423
lon_event = 178.026
dep_event = 33.9

# station location
lat_sta = 46.
lon_sta = 10.

# List of phases
phases = ['PcPPcPPKP','PcPPKPPcP','PKPPcPPcP']

# Plot the phase path
plot_phasepath(model, lat_event, lon_event, dep_event, lat_sta, lon_sta, phases, arrival=False, plot=True)
```

**Comment by kaspervanwijk** [comment]
It may be a limitation how the colour (cycle) is called in the source code
for the plotting function:

from obspy.taup import TauPyModel
model = TauPyModel(model="iasp91")
arrivals = model.get_ray_paths(source_depth_in_km=500,
distance_in_degree=130, phase_list=["ttbasic"])
ax = arrivals.plot_rays(legend=True)

also results in (some) different arrivals with the same colour.

**Comment by jrekoske** [comment]
It appears this problem was fixed for `'spherical'` style plots but not `'cartesian'` style.

Using the same example that okling provided I get the following results using `arr_path.plot_rays(plot_type='spherical', legend=True)` and `arr_path.plot_rays(plot_type='cartesian', legend=True)`.

obspy version: 1.3.0 (installed with conda)
python version: 3.7.10
macOSX

Could this issue be reopened?

![Raypath_spherical](https://user-images.githubusercontent.com/58538930/162328989-3c08b905-a469-42ec-9661-b819300468b4.png)

![Raypath_cartesian](https://user-images.githubusercontent.com/58538930/162328949-2f2bd096-efc1-47d8-865a-3560a6e121bc.png)
4117c7.png)
