### ISSUE TITLE
Filling SAC file headers / pysac

### ISSUE THREAD

**Issue by jorcubillos** [obspy/obspy#2594]
I need seismic waveforms from teleseismic events in sac format, Iḿ downloading these from IRIS using Obspy but when I write the sac files in my computer there is some missing information in the header. My questions are:

1. how can I install de PySac in anaconda?
2. can I solve my problem with PySac setting the missing information by myself?

thank you very much for your time, I really appreciate it.
cheers, and many thanks!

**Comment by jkmacc-LANL** [comment]
Hello, @jorcubillos!  PySAC is the same thing as the `obspy.io.sac` module in ObsPy, so you already have it installed 😄   If you have a `Trace` object, you can add more headers to it by populating the `tr.stats.sac` dictionary with SAC headers.  e.g.  If you want to add the event information:

```python
sachdr = {
    'evla': 12.34,
    'evlo': 123.45,
}

st = client.get_waveforms(...stuff...)
for tr in st:
    tr.stats.sac = sachdr
    tr.write(filename, format='SAC')
```
The `tr.write` call will look at the `sachdr` SAC header dictionary, and merge it with essential information from the `Trace` object `.stats` header.  Note: this will *not* make a SAC file that is event-based.  You'll have to do different things if that's what you want.

**Comment by jorcubillos** [comment]
ok, I bet that make a SAC file that is event-based is what I need, could you please explain me where I can find information to learn how to do it?

**Comment by jorcubillos** [comment]
The final question is how can I set Event origin time (seconds relative to reference time.) which header's field name is o? for example for an event with this origin time 2020-02-08T14:32:57, Julday=039.

many thanks.

**Comment by jkmacc-LANL** [comment]
Here's an example, using one of the traces that come with Obspy:

```python
In [32]: from obspy import read, UTCDateTime

In [33]: from obspy.io.sac import SACTrace

In [34]: sac = SACTrace.from_obspy_trace(read()[0])

In [35]: print(sac)
Reference Time = 08/24/2009 (236) 00:20:03.000000
	iztype IB: begin time
b          = 0.0
delta      = 0.009999999776482582
e          = 29.989999329671264
iftype     = itime
iztype     = ib
kcmpnm     = EHZ
knetwk     = BW
kstnm      = RJOB
lcalda     = False
leven      = True
lovrok     = True
lpspol     = True
npts       = 3000
nvhdr      = 6
nzhour     = 0
nzjday     = 236
nzmin      = 20
nzmsec     = 0
nzsec      = 3
nzyear     = 2009
scale      = 1.0
```

In this example, the trace is based on the time of the first sample (`iztype = ib` and `b = 0`).  You can also see that `sac.o` (the origin time relative to the reference time) is unset.  We can set it using a relative time or an absolute `UTCDateTime`, and the class will calculate the relative time to fill the header.  Let's pick an origin time just 3 seconds before the current reference time, then set it as the `sac.o` header:

```python
In [39]: otime = UTCDateTime('2009-08-24T00:20:00Z')

In [40]: sac.o = otime

In [41]: print(sac)
Reference Time = 08/24/2009 (236) 00:20:03.000000
	iztype IB: begin time
b          = 0.0
delta      = 0.009999999776482582
e          = 29.989999329671264
iftype     = itime
iztype     = ib
kcmpnm     = EHZ
knetwk     = BW
kstnm      = RJOB
lcalda     = False
leven      = True
lovrok     = True
lpspol     = True
npts       = 3000
nvhdr      = 6
nzhour     = 0
nzjday     = 236
nzmin      = 20
nzmsec     = 0
nzsec      = 3
nzyear     = 2009
o          = -3.0
scale      = 1.0
```

You can now see that the `sac.o` relative origin time is -3, since the origin was 3 seconds before the SAC reference time.  

We're halfway there.  Now, we need to tell the `SACTrace` instance that we'd prefer that the origin time be the reference time.  We do that by changing the `iztype` to `io`.  This will automatically adjust all the relative time headers:

```python
In [45]: sac.iztype = 'io'

In [46]: print(sac)
Reference Time = 08/24/2009 (236) 00:20:00.000000
	iztype IO: origin time
b          = 3.0
delta      = 0.009999999776482582
e          = 32.989999329671264
iftype     = itime
iztype     = io
kcmpnm     = EHZ
knetwk     = BW
kstnm      = RJOB
lcalda     = False
leven      = True
lovrok     = True
lpspol     = True
npts       = 3000
nvhdr      = 6
nzhour     = 0
nzjday     = 236
nzmin      = 20
nzmsec     = 0
nzsec      = 0
nzyear     = 2009
o          = 0.0
scale      = 1.0
```

You can see that the other times have been shifted such that `o` is 0.0, the reference time is the `UTCDateTime` that we supplied earlier, and the file is `origin type`-based.  

Now, you can `sac.write(filename)` to a binary file.

**Comment by jorcubillos** [comment]
Thank you so much, It worked very well!

**Comment by jkmacc-LANL** [comment]
Glad it worked!
