### ISSUE TITLE
Change tr.stats.property forever by adding 'inplace' keyword

### ISSUE THREAD

**Issue by Binhao-Wang** [obspy/obspy#2645]
When working with Obspy, I noticed a problem that when I change  a property in tr.stats, it works only temporarily. If I re-read in the stream again, the stats just remain unchanged.

As an example, if I run
```
st = read('*.BJT.[RTZ]')
tr_r = st[0]
tr_r.stats.channel = 'BHR'
```
It works if I `print(st)`. I will see the channel is now printed as 'BHR' as expected. But if I run `st = read('*.BJT.[RTZ]')` again, it is back to the initial state.

**Comment by Binhao-Wang** [comment]
I mean, it an `inplace=True` kwarg were added, it would be much more convenient than using `st.write('out.mseed',format='MSEED'`.

**Comment by d-chambers** [comment]
Hi @Binhao-Wang ,

When you call `obspy.read` obspy reads the file from disk into memory (RAM). Any changes to the ObsPy objects only occur on the data in RAM, the python object is completely disassociated from the file (by design). While it would, in theory, be possible for ObsPy to keep changes synchronized between the file and the python object it would require very complicated (ie error-prone) code and be bad practice. So, by design, you are stuck with explicitly saving the stream to disk if you want a change to persist. Anyway, one extra line of code is not so bad :wink:

**Comment by Binhao-Wang** [comment]
Thanks for your explaination! I am not familiar with all these backgrounds and now I understand. Hope Obspy will get better and more popular in the future.

**Comment by megies** [comment]
> Hope Obspy will get better and more popular in the future.

:eyes:
