### ISSUE TITLE
ImportError while using read function

### ISSUE THREAD

**Issue by LevCarlo** [obspy/obspy#2669]
> Platform: aarch64 GNU/Linux

ImportError: Could not load shared library "libmseed_Linux_64bit_py37.cpython-37m-aarch64-linux-gnu.so"
  Path: /root/archiconda3/envs/obspy/lib/python3.7/site-packages/obspy/lib/libmseed_Linux_64bit_py37.cpython-37m-aarch64-linux-gnu.so
  Current directory: /root/Jupyter

**Comment by megies** [comment]
Installed via Anaconda with "conda install"?

**Comment by LevCarlo** [comment]
> Installed via Anaconda with "conda install"?

While using "conda install", it shows there is no channels available. So I dowload the source file "obspy-1.2.2-py37h03ebfcd_0.tar.bz2" , upload to Cloud Server and installed with "conda install --use-local obspy-1.2.2-py37h03ebfcd_0.tar.bz2". I can import ObsPy successfully, but when I use read function it report an error like this.

And I uninstalled with "conda uninstall" and installed with "pip", when I use read function it report this error agian.

**Comment by megies** [comment]
Did you specify `conda-forge` channel when installing (like shown in the installation wiki)? Because otherwise it simply can't ever find obspy. If you did you might be on a platform that conda-forge is not building packages for..?

If you eventually install with pip anyway, you don't even need to do these gymnastics about the obspy package, just make sure to install all dependencies with `conda install` beforehand and then `pip install obspy`. You can do this with trial and error if needed. If your `pip install obspy` is pulling in more packages, just make the environment from scratch again and install those with conda too.

Lastly, it sounds like a naming problem of the libraries, and i might have some advice for workarounds, but before elaborating please confirm you tried/followed the above leads first.

**Comment by megies** [comment]
Please reopen if needed
