### ISSUE TITLE
Waveform Plotting - number of ticks option issue

### ISSUE THREAD

**Issue by CoralieAubert** [obspy/obspy#2727]
Hello,

I am facing an issue when plotting waveforms with Obspy.

I would like to plot 10 minutes of trace and increase the number of ticks to have a tick every minutes on the x-abscisse of the graph.

It seems the number_of_ticks option of the plot() function does not work.

I have been using the scripts here under which is very simple:
```
st=read(file.miniseed)
st.trim(starttime=t1,endtime=t2,fill_value=0,pad=True)
st.plot(outfile=outfile,number_of_ticks=10) 

```
Do you have an idea?

Coralie

**Comment by megies** [comment]
Looking at the source code, `number_of_ticks` is only ever used in `dayplot` mode. I see it in a [normal plot example in the docs](https://docs.obspy.org/tutorial/code_snippets/waveform_plotting_tutorial.html?highlight=number_of_ticks), so that should be taken out there.

You probably have to adjust the plot yourself, not saving to `outfile` but using `show=False` and then working on the returned figure object, setting new [tick locator and/or tick formatter](https://matplotlib.org/3.3.2/api/ticker_api.html). Also maybe see [our formatter we use](https://github.com/obspy/obspy/blob/cd1e51208cf06419a328fa3021cda52b57a35a07/obspy/imaging/util.py#L91) for reference.

**Comment by megies** [comment]
Closing this for now, I don't think we want to add a new option here for the normal plot, this is the kind of customization we should leave to the user, I think. Feel free to reopen if needed.

**Comment by megies** [comment]
see https://github.com/obspy/obspy/commit/0ec50fb75cff5cc85df2293dc677d2e84a148060
