### ISSUE TITLE
Instrument response (total gain does not match the computed sensitivity)

### ISSUE THREAD

**Issue by hadighasemi** [obspy/obspy#2756]
Hi Team,

First of all, apologies if this is not the right forum to raise this issue, but was hoping that someone may be able to help 👍 

I am trying to create a response object using "Response.from_paz" class. I noticed that sometimes there is a mismatch between the computed total gain and overall sensitivity values ( and of course sometimes they do match )! I assumed that overall sensitivity is simply the multiplication of the gains of all of the stages, am I wrong? 

Here is a sample script: 
[sample_response.py.txt](https://github.com/obspy/obspy/files/5600230/sample_response.py.txt)
in this example, the total gain is 8.5e+8 while the sensitivity is much larger at 1.2e+09!

Cheers
H

**Comment by WayneCrawford** [comment]
Hi,
I think the gain is a constant value, whereas the sensitivity is evaluated at a given frequency.  The gain and the sensitivity are identical (or close) in the passband only if there are the same number of poles and zeros.  Practically speaking, this means that there are no lowpass filters cutting off the high-frequency response above the passband.  The Pole-Zero equation is  (from Seed Manual v2.4, Appendix C):
```
G(f) = S_d * A_0 * prod(s - z_n) / prod(s - p_n) = S_d * A_0 * Hp(s)
```
where `s=j*2*pi*f`, `S_d` is the gain, `A_0` is the norm_factor and `G(f)` is the sensitivity at frequency `f`.  `G(f0)` is the passband gain, with `f0` the reference frequency.

`A_0` should be set so that `A_0 * prod(s-z_n)/prod(s-p_n) = 1` at `f0`.

If there are the same number of poles and zeros, the products cancel each other out above the hightest pole and zero frequency, so `A0=1` and `G(f0) = S_d`

If there are more poles than zeros (the usual case), each "extra" pole divides by `j*2*pi*f` in the passband, so gain and sensitivity are not the same.

This is not very well documented in obspy, in my opinion because there isn't a PZ class that can assemble all of the functions and docstrings (see issue #2747)

Regards
Wayne

**Comment by trichter** [comment]
Adding to that, in the case of the PAZ in the sample script, three of the five poles are far away from 0j. Therefore, there is a plateau starting at ~2Hz going up to reasonable high frequencies.

The reason for the discrepancy here is that you define the gain for the PAZ at 1 Hz, which is not yet in the plateau. You can see in the plot, that the sensitivity at 1 Hz is indeed exactly the value you specify. If you exchange `Response.from_paz(zeros, poles, total_gain, 1.0 -> 5.0` you will see the expected result.

**Comment by megies** [comment]
@hadighasemi ideally please use the Discourse forum at https://discourse.obspy.org/ for usage questions, thanks!
