### ISSUE TITLE
StationXML long dates for Network

### ISSUE THREAD

**Issue by WayneCrawford** [obspy/obspy#2817]
StationXML files created using Inventory.write() used to have short dates (`YYYY-mm-dd`) in the network field, but they now include `THH:MM:SS.ffffffZ`.  I don't know if this is deliberate, but FDSN prints short dates and temporary networks often end on `YYYY-12-31`, which could cause some problems because now it will be interpreted as the start of the last day of the year and not the entire day.

I was wondering if this change was deliberate or if it just slipped in?

I attached an [example](https://github.com/obspy/obspy/files/6203218/station_write.txt)
 (named .txt instead of .py so that GitHub would accept it), which is just the STATIONXML creation  example from the tutorial page.  In obspy v1.1 (and maybe 1.2.1?) the network line woud be:

```
  <Network code="XX" startDate="2016-01-02">
```

it is now 
```
  <Network code="XX" startDate="2016-01-02T00:00:00.000000Z">
```

Installation information:
-  ObsPy version 1.2.2, Python version 3.8.6, Platform = OSX (11.2.3)
-  ObsPy and Python installed using anaconda

**Comment by megies** [comment]
I'm inclined to close this, for two reasons

 - would it even matter to have `YYYY-12-31T23:59:59.999999` in that field instead of (semantically) `YYYY-12-31T00:00:00.000000` or even `[YYYY+1]-01-01T00:00:00.0` (which seems what semantically is wanted)?
 - `YYYY-12-31` simply is equivalent to `YYYY-12-31T00:00:00`, no matter how you look at it and even if we were to write the former into StationXML, it'd still semantically be identical to "start of Dec. 31".

Especially with the second argument, I think there is nothing to be done about this.

**Comment by megies** [comment]
Also, FDSN StationXML schema defines all date/time values as `xs:dateTime` it seems and it looks like for that type, everything is mandatory except the optional decimal seconds and time zone part.
