### ISSUE TITLE
Ambiguity in xcorr_max()

### ISSUE THREAD

**Issue by Lewis-Khan** [obspy/obspy#2820]
The [documentation ](https://docs.obspy.org/packages/autogen/obspy.signal.cross_correlation.xcorr_max.html) for `xcorr_max()` has a boolean for `abs_max` to define whether to take the maximum cross correlation or not. My confusion lies since absolute in mathematics often defines a positive value. When `abs_max = True` it allows the maximum positive OR negative value. This is opposite to what I expected since "abs_max" should imply positive? Is there a way of adding clarification/changing the variable name?

Cheers!

**Comment by trichter** [comment]
@Lewis-Khan Could you create a PR with a better doc string? I think returning the negative value for the case of a "negative absolute maximum" is preferable since it transmits more information.

**Comment by Lewis-Khan** [comment]
@trichter Yes, I can give it a go. Just to make sure i'm along the right lines it should be:
```
if abs_max == True:
    Return the maximum positive correlation.
elif abs_max == False:
    Return the maximum correlation (positive or negative)
```
Should the default value for the function then be switched from abs_max = True to abs_max = False to switch the meaning? If so, this may change existing code.

Which branch should I submit a pull request on - master or maintenance?

**Comment by trichter** [comment]
I think it is not an option to change the behavior of the code. Better only clarify the doc string. `abs_max=False`(default) -> maximum (always positive) , `abs_max=True` -> absolute maximum (positive or negative).

Usually this would go into maintenance. But at the moment I'd prefer master, because maintenance still supports python2. We'll probably not see another `1.2.x` release. Later when maintenance is merged into master, it will land in master anyway, but the merging itself is another step and might result in more work when eliminating any merge conflicts.
