### ISSUE TITLE
Could not build wheels for obspy which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by benkalyx** [obspy/obspy#2834]
I'm running python 3.9 and i tried to install using pip but I keep getting the error message, 'Failed building wheel for obspy;

**Comment by martanto** [comment]
I have the same error. Upgrading pip not solve the problem either. Downgraded python to 3.8 and everything is working fine.

**Comment by ThomasLecocq** [comment]
Hi, please prive more information for this, as required in the Issue Template:


* Please check whether the bug was already reported or fixed.
* Please provide the following information:
  -  ObsPy version, Python version and Platform (Windows, OSX, Linux ...)
  -  How did you install ObsPy and Python (pip, anaconda, from source ...)
  -  If possible please supply a [short, self contained, correct example](http://sscce.org/) that
     demonstrates the issue.
  -  If this is a regression (used to work in an earlier version of ObsPy),
     please note when it used to work.
* Please take the time to [format your ticket appropriately](https://guides.github.com/features/mastering-markdown/)
  (e.g. put error tracebacks into code blocks)

**Comment by ThomasLecocq** [comment]
probably all solved by now, closing (reopen if problem still exists)

**Comment by shan-ying** [comment]
I have this error when I install the obspy on Python3.7 in CentOS7

I used pip to install obspy, and it's version is obspy-1.3
The error message include many "Package would be ignore", the image only show the first one.
And in the last of install message show "Could not build wheels for obspy which use PEP 517 and cannot be installed directly".

[Package version& Environment]
CentOS 7
Python 3.7.3
numpy 1.21.2

In linux
It will success if use python3.8 to install, but I need use this package in python3.7 in CentOS7.

In windows
Python3.7 can success to install and use, but need install some other C++ package(It will show in the process of install)

If someone solve this issue, please tell me.
Appericate.

![image](https://user-images.githubusercontent.com/18310015/186802502-c8ec53bd-ab9e-4930-a4b7-ea066667018b.png)
