### ISSUE TITLE
Resource-ID linking sometimes fails when reading Quakeml-files in parallel

### ISSUE THREAD

**Issue by flixha** [obspy/obspy#2842]
When I read in Quakeml-files in parallel, then the linking of referred objects often does not work. In the cases where it doesn't work, it appears that all `_object_id` are set to `None` (e.g., `cat[0].origins[0].resource_id._object_id`) instead of a  hashed number. I certainly don't understand all what is happening under Obspy's hood to to the hashing, but the problem seems to appear when python is using a new process to read a Quakeml-file.

Can someone who knows the hashing part well comment if they have any ideas what's going on?

Consider the following example:
```python
from obspy import read_events
from joblib import Parallel, delayed

def check_references(cats):
    if cats[0][0].preferred_origin() is None:
        print('cannot find referred origin-object')
    else:
        print('Test successful')


cats = Parallel(n_jobs=2, prefer='processes')(
    delayed(read_events)()for j in range(2))
check_references(cats)

cats = [read_events() for j in range(2)]
check_references(cats)

for i in range(5):
    cats = Parallel(n_jobs=2, prefer='processes')(
        delayed(read_events)()for j in range(2))
    check_references(cats)
```

**Tested on 2 machines:**
  -  ObsPy 1.2.2 / master from github installed in conda, Python 3.8, Linux RHEL 8.3
  -  ObsPy 1.2.2 / master from github installed in conda, Python 3.6, MacOS 10.13

Test 1 output (python run from terminal on both machines):
```
cannot find referred origin-object
Test successful
Test successful
Test successful
Test successful
Test successful
Test successful
```

Test 2 output (ipython-jupyter-window in VSCode on 1st machine):
```
cannot find referred origin-object
Test successful
Test successful
Test successful
cannot find referred origin-object
cannot find referred origin-object
cannot find referred origin-object
```

**Comment by d-chambers** [comment]
Hey @flixha,

Unfortunately you have stumbled on one of the rough edges of ObsPy. The `ResourceIdentifier` has never really worked all that well. I did some work on it a few years back so that it would at least return objects scoped within the same `Event` (before it was anyone's guess what it might do if you had objects with duplicate resource ids) but I never had multiprocessing in mind in that case. See #2091 and #2279.

I strongly suspect the reason this doesn't (and perhaps can't) work within multiprocessing is that the `ResourceIdentifier` object keeps a few dicts with global state mapping the resource ids to the correct objects with weak refs. Multiprocessing doesn't share memory so the correct look ups from the catalog created in a foreign process aren't preserved when the catalog is re-serialized into the current process.

The good news is there is a workaround. The correct resource ids still exist, you just need to create a link between the resource_id and  the object it points to. [Here](https://github.com/niosh-mining/obsplus/blob/8483b6778ad74158884b55ed9820caf3f2a239e4/obsplus/events/validate.py#L42-L57) is a function which does that. It recurses the event tree and constructs a graph which links each resource_id back to the correct object, then attaches them. The downside, however, is that you may lose any speed-ups you get from reading events in parallel if you have to call this new function to make sure resource_ids work properly. :shrug:

**Comment by d-chambers** [comment]
Ok, glad you still see some speed ups. Does your hardware actually support parallel IO or is the bulk of time in parsing the xml and converting it to python objects?  #1910 highlights some of the performance issues with the current implementation.

I wonder if saving the events as json and using a fast json parsing library (eg orjson) would alleviate the need to use multiprocessing altogether. [Here](https://niosh-mining.github.io/obsplus/versions/latest/notebooks/utils/json.html) is an example of converting a catalog to/from json if you are inclined to try it on your test dataset.

As far as addressing this issue goes, I don't think we have a way to fix ObsPy's `ResourceIdentifier` to handle multiprocessing without moving to a completely different implementation. I have some ideas how this might be done, but I am not in a position to undertake it at the moment. Perhaps we should close the issue?

**Comment by flixha** [comment]
The limiting factor is definitely the XML parsing. While I'm not testing on a parallel filesystem right now, reading the 3 hours for 3 GB Quakeml seems to point towards the CPU clearly - which I can see at the CPU load when reading in parallel. 

As I had downloaded the Quakeml-files from a webservice, I was first afraid that they were somehow corrupted when the linking did not work, so now it's good to know where the issues is coming from and how it can be worked around. I had looked into #1910  just a bit before, and I see I'll have to experiment a bit more for the general I/O after I have now properly read in the catalog once.

I did a quick check on the json-conversion that you linked; but for this to work I'll have to do  some more checks / fixes for `None`-values in the catalog.
Just as a comparison; reading the catalog from a pickle-file where the catalog-object is dumped is about 10 times faster than reading Quakeml (which I still find is not thaaat quick), but that also needs the resourceID-fixing.

As  you suggest, if this issue can't be fixed right now because it needs more fundamental changes, we can close it.
