### ISSUE TITLE
after merge and/or trim, trace.stats.sac['npts'] isn't updated

### ISSUE THREAD

**Issue by jwebster-LANL** [obspy/obspy#2861]
In traces with sac header info, after stream.merge, stream.trim, trace.trim, trace.slice and I'm guessing other similar operations that change the number of points in a trace, trace.stats.npts is updated, but trace .stats.sac['npts'] isn't.

This could generate a large amount of confusion if someone is merging/trimming and using the sac headers for the number of points.

**Comment by jkmacc-LANL** [comment]
Hi.  The `.stats.sac` isn't meant to be live in the way that `.stats` is.  Keeping them both in sync at all times could be difficult and unnecessary in most use cases.  When the trace is written back to SAC, the old header is merged with the ObsPy header and that's when those values are updated in the resulting file.  Is this working properly?  If you're using an ObsPy Trace, the up-to-date header is `.stats`.

**Comment by jkmacc-LANL** [comment]
This is interesting.  I agree that it could cause confusion, and I don't know OTOH why they'd return something different.  I'd encourage anyone looking for Trace metadata to use `.stats` instead of `.stats.sac`, though.  The latter isn't meant to be live in the same way as the former.

**Comment by jkmacc-LANL** [comment]
I wonder if it's related to the stats/sac header values having the same name.

**Comment by megies** [comment]
This is expected behavior. Basically, whatever is in those separate header fields never gets touched when meddling with `Trace` / `Stream` methods. Those objects are completely oblivious and ignorant towards file format specific headers.

The only time these things get touched is when reading or writing a trace with a certain I/O plugin. The plugins itself are the only things ever setting or re-using these file format specific headers.

I'm pretty sure it is pointed out somewhere in the docs that these are specific to certain file formats and are for more advanced use cases.

I'm closing this for now, @jkmacc-LANL feel free to reopen if this is a problem for `io.sac` in case it is using that field on output, writing bad metadata.
Anybody feel free to open PRs with improvements to docs, to better explain this to people.
