### ISSUE TITLE
NLLoc rejected locations & phases added in nlloc.core

### ISSUE THREAD

**Issue by erhmestel** [obspy/obspy#2986]
NonLinLoc outputs hyp files for each location, they can be read into an obpsy catalog object ([source code](https://docs.obspy.org/_modules/obspy/io/nlloc/core.html#_read_single_hypocenter)). 
**Currently obspy reads in rejected locations and rejected arrivals in the same way as those that are not rejected.**

obspy 1.2.2, python 3.7.3 - install from conda-forge in an anaconda environment on Ubuntu 18.04.4
using nonlinloc 7.0
Can't find any mention of this in other issues raised previously

# Origins
I have seen two types of locations in hyp files (there may be others). Currently both are processed in the same way:
- a successful location. The first line of each hyp file for a successful location reads something like:
> NLLOC "./locs/test_loc/test.20220101.000000.gri0" "LOCATED" "Location completed."
- a location which was completed but was then rejected for being on the boundary of the search region. The first line of each hyp file for a rejected locations reads something like:
> NLLOC "./locs/test_loc/test.20220101.000000.gri0" "REJECTED" "WARNING: max prob location on grid boundary 10, rejecting location."

I have attached two example hyp files (one for a successful location [test_located.txt](https://github.com/obspy/obspy/files/8084723/test_located.txt) and one for a rejected location [test_rejected.txt](https://github.com/obspy/obspy/files/8084727/test_rejected.txt)).

I don't think the fact that NLLoc rejects the location is currently marked in the created origin in any way - it probably should be? Maybe they shouldn't be included at all.

# Arrivals
The hyp file lists the phases related to the location: both those which are used, and those which are rejected are listed. Similarly to the above, currently obspy reads in all of these as arrivals for each origin. 

The fact that NLLoc rejected the arrival is not specifically marked, but rejected arrivals seem to have:
- azimuth 359.0
- distance 0.0
- takeoff_angle -1.0
- time residual 0.0
- time_weight 0.0

and you can identify the origins with the problem:
`if len(origin.arrivals) == origin.quality.associated_phase_count and len(origin.arrivals) != origin.quality.used_phase_count:`

An example of a hyp file with rejected arrivals can be found in [test_rejected.txt](https://github.com/obspy/obspy/files/8084727/test_rejected.txt) (note: you do also get rejected phases in hyp files for locations which are not rejected).

**Comment by megies** [comment]
> I don't think the fact that NLLoc rejects the location is currently marked in the created origin in any way - it probably should be? Maybe they shouldn't be included at all.

Well, Nonlinloc returns full location output and only mentions "rejected" as text in the comment line.. so I dont see why we shouldn't read that file. I'd probably suggest setting the [event type](https://docs.obspy.org/master/packages/obspy.core.event.header.html#obspy.core.event.header.EventType) to "not reported" and maybe the [event certainty](https://docs.obspy.org/master/packages/obspy.core.event.header.html#obspy.core.event.header.EventTypeCertainty) to "suspected".
Indeed it looks like right now any text in the initial `NLLOC ....` line isn't parsed, we could parse that into a `Comment` maybe.

> lists the phases related to the location: both those which are used, and those which are rejected are listed

I only see one "rejected" phase and nonlinloc states the "weight" as `0.0` which also gets stored in `Arrival.time_weight`, so you can actually tell the "rejected" lines I believe. So, I think we should be fine regarding this matter?
n.b.: Note that that phase states the station coordinates as -1000000000000, so there might be an issue with your station coordinates?

**Comment by megies** [comment]
But yes.. if we could confirm with @alomax that such "rejected" phases always have the same "bogus" values, we could parse it as a pick but not create an Arrival from it maybe.

**Comment by erhmestel** [comment]
> n.b.: Note that that phase states the station coordinates as -1000000000000, so there might be an issue with your station coordinates?

Yes - in this example MAVZ is a station picked but not defined in the NLLoc set up.  The other instance I know of when picks are rejected is when the phase marker is one which is not being used - e.g. when S picks are being rejected, as below (copied from a different hyp file):
> BEEZ   ?    Z    ? S      ? 20201209 0634   50.1568 GAU -1.00e+00 -1.00e+00 -1.00e+00 -1.00e+00 >    0.0000    0.0000    0.0000   42.6331   56.3267   -0.5720    0.0000   0.00 359.0  -1.0  0     0.0000

As you say, it could be that reading in `Arrival.time_weight = 0` is sufficient.

**Comment by alomax** [comment]
Hi all,

For arrivals, it is correct that station coordinates as -1000000000000 is a good indicator that the phase reading was rejected on input - this is usually (always?) because there is no travel-time grid file available or no station location (GLOBAL mode) for this station and phase:

`NC_PTA       ?    Z    e P      ? 20220130 2047   45.1000 GAU  1.00e-01 -1.00e+00 -1.00e+00 -1.00e+00    1.0000 >    0.0000    0.0000    0.0000 -100000000000000000000.0000 -100000000000000000000.0000 -100000000000000000000.0000    0.0000   0.00 359.0  -1.0  0     0.0000    0.0000
`

Zero-weight, however, may also occur for valid station/phases for which there is an available travel-time grid. Zero weight can be (somewhat ambiguously): 

- With GAU_ANALYTIC the weight is prior, and can occur for a reading that has very large pick or travel-time uncertainty.
- With EDT the weight is posterior and can occur for a reading that has very large residual at the maximum likelihood hypocenter. The above prior case can also occur with EDT
- When LOCEXCLUDE or LOCINCLUDE is used to exclude or explicitly include sets of station/phases from location, the weight will be zero, but residual non-zero for excluded station/phases.

"The other instance I know of when picks are rejected is when the phase marker is one which is not being used - e.g. when S picks are being rejected, as below"

How are you rejecting S picks in this case?

Anthony

**Comment by erhmestel** [comment]
It as a while ago I was messing aorund with only using P arrivals, so I have gone back and checked. The above instance was with no S velocity or travel time grids built, but -1 for `VpVsRatio` in the `LOCMETH` line.

Just tested  - when I mapped S to $ `LOCPHASEID $ S` then S arrivals were not read in and do not appear in the hyp file.

With `LOCPHASEID  S   S s G SN SG`
> ... 43 observations read, 43 will be used for location (./locs/20201030_find_s_waves_loc.20191027.064125).

With `LOCPHASEID $ S`
> ... 23 observations read, 23 will be used for location (./locs/20201030_find_s_waves_loc.20191027.064125).

**Comment by alomax** [comment]
Hello @erhmestel

Thanks for the details. Yes, this is exactly the behavior I see. "$" is a special phase code to completely reject a phase pick observation.

Anthony
