### ISSUE TITLE
Dependency versions for next major release

### ISSUE THREAD

**Issue by trichter** [obspy/obspy#3016]
> check dependency versions, some old distros we used to support might have gone EOL since release of 1.2, so we might be able to bump minimum dependency versions of e.g. numpy, scipy, matplotlib, ...

After #2929 is nearly finished, I would like to discuss the minimal dependency versions. Related  #2508. When we loosely follow [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) and do not expect the next major release to land for at least a year, it would be good enough to support python3.9+ and numpy 1.20+.

**Comment by trichter** [comment]
@megies What do you thin about this one? Removing not needed python test runs in master will also save CI time.

**Comment by megies** [comment]
Sounds good to me. I just had a look at Debian and even their one year old current stable is on 3.9. I dont have a problem dropping <3.9 on master even right now :+1:



> and do not expect the next major release to land for at least a year

In principle, I think we could (and maybe should) do major releases way more often. Doing those used to be a big effort, mostly self-imposed, with us going crazy with running tests in a dozen or more docker images of various Linux distros and also by several packaging efforts through all kinds of channels.

Since right now, we pretty much only do pypi and conda-forge, and that's mostly automated even, doing a release should be a matter of an hour or two at most, compared to the weeks long back and forth we used to have (also due to dragging dependency minimum version bumps out so much).

Making contributions end up in conda-installable releases much faster might also encourage people to contribute and show activity in the project more. I would be discouraged contributing something, if it subsequently is hanging on an unreleased master branch for a year or more (and that's what used to be the case for the most time).

**Comment by trichter** [comment]
For the CI I had to set minimum matplotlib version to 3.3. Older packages are not available via conda for python3.9.

Summing it up, tested minimal versions are:
```
python 3.9
numpy 1.20
scipy 1.7
matplotlib 3.3
```

**Comment by megies** [comment]
@trichter you want to set those on master branch for next major release?

**Comment by trichter** [comment]
@megies only if that is OK with you/everybody who cares.

**Comment by megies** [comment]
I dont think anybody will speak up here :rofl: so it's mostly up to us to decide I think. Don't see a reason not too and we probably dont wanna state support for versions that we dont test, so I'd just up dependency version numbers in general, probably, or we might get confused ourselves eventually :grimacing:

**Comment by trichter** [comment]
Yes we can make it explicit in the setup.py's `INSTALL_REQUIRES`. ObsPy or parts of it might be running  accidentally on lower dependency versions, though.

**Comment by megies** [comment]
> running accidentally on lower dependency versions, though.

Nope. People won't be able to use it with lower versions, since setuptools will throw an Exception if it notices the dependency versions in setup.py are not met

**Comment by trichter** [comment]
> > running accidentally on lower dependency versions, though.
> 
> Nope. People won't be able to use it with lower versions, since setuptools will throw an Exception if it notices the dependency versions in setup.py are not met

Ah, OK, I thought there might be a way to circumvent these exceptions, e.g. `--no-deps` flag.

**Comment by megies** [comment]
> Ah, OK, I thought there might be a way to circumvent these exceptions, e.g. `--no-deps` flag.

Pretty sure setuptools checks every time at runtime when using "import ..."

**Comment by heavelock** [comment]
> @megies only if that is OK with you/everybody who cares.

Hey! Sorry for my lack of engagement in past year. I departed from seismology but I still care about obspy :) 

To be honest, I think obspy should keep pace of the ecosystem. What I mean by that, is that it should keep dependencies more or less in sync with numpy's as well as it should be released on more frequent basis. Since you managed to finalize new build system that makes releases less of a chore, I think it looks good for a project if it is released more often than every few years and contributors might also be more likely to contribute in the project if they will know that their code will be released in some timely manner. I saw that this topic was also mentioned somewhere in the conversations over here.
