### ISSUE TITLE
cannot find the link to download the pdf doc

### ISSUE THREAD

**Issue by wangliang1989** [obspy/obspy#3033]
### Documentation Link

https://docs.obspy.org/tutorial/index.html

### Problem

I cannot find the link to download the pdf doc. This 'here' cannot be clicked:

<img width="934" alt="image" src="https://user-images.githubusercontent.com/12059719/160561496-b9e48e31-201b-4935-a093-b1a69253ce0b.png">

### Suggested improvement

Just provide the link to download pdf doc.

Thank you

**Comment by megies** [comment]
Hmm.. I cant find it, the pdf might not get built currently, the docs building went through some major changes recently (mostly #2662 i think) and maybe the pdf building got left out in the transition.

You can get the pdf for version 1.2.0 here: https://docs.obspy.org/archive/1.2.0/_downloads/ObsPyTutorial.pdf

Changes in Tutorial over time can be seen [here](https://github.com/obspy/obspy/commits/master/misc/docs/source/tutorial), but there might not be too many important changes since 1.2.0 that you would have to worry about, probably.

**Comment by wangliang1989** [comment]
> https://docs.obspy.org/archive/1.2.0/_downloads/ObsPyTutorial.pdf

Thank you

**Comment by lpk-py** [comment]
> 

hi thomas,

can u compile all docs into pdf (not only the tutorial) plz? or provide a guide on how to compile

we always prefer reading printed rather than on screen.

thanks.

**Comment by trichter** [comment]
We only deliver html at the moment. The docs are build by the docs building workflow in Github Actions. At the moment it runs only `make html`.
