### ISSUE TITLE
Different plotting style for P- and S-waves

### ISSUE THREAD

**Issue by jrekoske** [obspy/obspy#3042]
### Problem

It would be nice when plotting ray paths with `obspy.taup.plot_ray_paths()` to distinguish between P- and S-waves. As an example, see this Figure 4.15 from Shearer Introduction to Seismology that uses squiggles (sine waves) for S-waves. There could be other ways to do this too (e.g., different matplotlib line styles) Currently `plot_ray_paths` makes solid lines for all ray types.
![raypaths](https://user-images.githubusercontent.com/58538930/162472074-58fa58a1-370a-4d01-84fc-20ccae4483d4.png)

### Proposed solution

Modify the `plot_ray_paths` plotting code to distinguish between P- and S-waves, either with squiggly lines or different line styles.

**Comment by johnrudge** [comment]
I have had a first stab at addressing this issue here:
https://github.com/johnrudge/obspy/commit/8bd4e95faab5e4aadaa061d3801bac8b84176abc
It adds an "indicate_wave_type" flag to the plot_rays method of the Arrivals object to plot the S waves as wiggly lines. Would the obspy developers like me to make a pull request?
Here's a PKJKP example:
![PKJKP](https://user-images.githubusercontent.com/43536815/162752578-98cc450a-f5ae-4088-9282-05f4c23eb60a.png)

**Comment by megies** [comment]
> Would the obspy developers like me to make a pull request?

Personally, I think this is awesome, so.. do it!

I've merged #3041 into master so please start from current master again which already has that fix for color cycling for cartesian plot.

Maybe linewidth for the wiggle part needs to be a bit higher?

**Comment by johnrudge** [comment]
Thanks! I've merged in the latest changes from master and have submitted the pull request. I also made the linewidth a little thicker on the wiggly parts.
