### ISSUE TITLE
Memory leak in Routing Client

### ISSUE THREAD

**Issue by KlausStammler** [obspy/obspy#3120]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

The example code (requesting data from a single channel using the RoutingClient) does not return and slowly eats up all memory of the machine. Tested with python3 (3.6.9) on two hosts running Ubuntu 18.04.6 LTS, obspy version 1.1.1. obspy was installed using "apt-get" (without conda), on one machine it was a fresh install.

When changing the client to a direct connection to RESIF ("Client( 'RESIF')") the programs complains about missing data and exits.

### Code to Reproduce

```python
from obspy import UTCDateTime
from obspy.clients.fdsn import RoutingClient, Client

orig = UTCDateTime("2022-07-09T11:47:30")

roc = RoutingClient( "eida-routing" )
data = roc.get_waveforms( network='FR', station='BETS', location='*',
    starttime=orig-10, endtime=orig+80, channel='HHZ' )
```

### ObsPy Version?

1.1.1

### Operating System?

Ubuntu 18.04.6

### Python Version?

3.6.9

**Comment by megies** [comment]
It's not a mem leak, but actually requesting the whole EIDA archive ;)
This was fixed in #2611 which is included in obspy 1.2.2, see [changelog](https://github.com/obspy/obspy/blob/571f15918f56430d7891305a86be138c4c499b61/CHANGELOG.txt#L238-L241)

Sadly Debian Python packaging is really painful and it just took too much time to figure out why the packaging setup I had stopped working for newer distros. But you really should update to a more recent obspy version. If you don't want to have a dedicated Python environment, you could try `pip install obspy` as root, adding to the system Python. I am relatively certain that Debian has `pip` patched so that it does not install in the directory apt packages get installed to but a different directory so that it does not get messy in the folders handled by apt.
