### ISSUE TITLE
option to split event requests to circumvent datacenter restrictions

### ISSUE THREAD

**Issue by filefolder** [obspy/obspy#3202]
### Problem

Is this needed? I find myself having to do this often enough to create this post, plus I recall some users here being thwarted by this, but equally likely this is too esoteric to address. 

### Proposed solution

I suppose my idea would be to add a `split_requests=1` kwarg to `get_events` where anything over the default 1 would split the time windows and loop through them as separate requests, e.g.

```
t_ = np.linspace(start.timestamp,end.timestamp,split_requests)
for i in range(len(t_)-1):
    try:
        catalog += xyz.get_events(starttime=t_[i],endtime=t_[i+1])
    except:
        pass
```
thumbs up thumbs down?

(this also allows a shortcut to try/except around empty request errors i suppose...)

**Comment by megies** [comment]
In principle that's what `limit` and `offset` parameters are for. The only painful part is that it is kinda hard (or impossible?) to tell what the best values for pagination are..

```python
limit = 1000
offset = 0  # FDSN docs say default is 1, so maybe 1 here
cat = Catalog()
while True:
    new = client.get_events(..., limit=limit, offset=offset)
    cat += new
    if len(new) < limit:
        break
    offset += limit
```

I guess we *could* add an option `auto_pagination=True` or something that kicks in if a) the original event request returns HTTP 413 **and** b) limit and offset weren't specified explicitly.
It might not be trivial to do though, I guess, since even with pagination you could run into another paginated request being too big (if some particular event has an unusually huge data footprint).

Other opinions?

**Comment by filefolder** [comment]
On second thought I think at the moment this is still not an issue enough to make any actual changes and it's easy enough to DIY, but once these ML catalogs start hitting the shelves people may start running into this more often. Happy to let this sink if/until that happens.
