### ISSUE TITLE
Somtimes the client "IRIS" not available

### ISSUE THREAD

**Issue by JUNZHU-SEIS** [obspy/obspy#3298]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

When I run
```
from obspy import UTCDateTime, read
from obspy.clients.fdsn import Client
import os

source = "IRIS"
stationfile = "./IRIS.sta"
tracedir = "./Trace/20190704/"
tb = UTCDateTime("2019-07-04T00:00:00.00")
te = tb+86400
client = Client(source)
```
I got
```
Traceback (most recent call last):
  File "data_download.py", line 18, in <module>
    client = Client(source)
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/clients/fdsn/client.py", line 277, in __init__
    self._discover_services()
  File "/home/lilab/jzhu/.local/lib/python3.8/site-packages/obspy/clients/fdsn/client.py", line 1638, in _discover_services
    raise FDSNNoServiceException(msg)
obspy.clients.fdsn.header.FDSNNoServiceException: No FDSN services could be discovered at 'http://service.iris.edu'. This could be due to a temporary service outage or an invalid FDSN service address.
```

### ObsPy Version?

1.4.0

### Installation Method?

None

**Comment by JUNZHU-SEIS** [comment]
A sidenote: when I change the client into "SCEDC", it works. But this is not my expected data center.

**Comment by megies** [comment]
This looks like a classical network problem. It takes two to tango, so the problem is either on IRIS' side (or should rather say EarthScope) or your side, or less likely somewhere in between. In general, I would doubt that IRIS has frequent noticeable problems, but if you really think the problem is not on your end then you should contact IRIS/Earthscope about this (you can find an email address at the bottom of e.g. [this page](http://service.iris.edu/fdsnws/station/1/)).

**Comment by megies** [comment]
When the problem occurs again, you might wanna repeatedly try to connect to "IRIS" fdsnws and see if it works on repeated tries while at the same time making sure your network connection does not have a short interruption (e.g. open some web page that isn't in your brower cache)
