### ISSUE TITLE
SAC: Potential problem with floating point accuracy in sampling rate / sample spacing

### ISSUE THREAD

**Issue by megies** [obspy/obspy#3408]
### Avoid duplicates

- [X] I searched existing issues

### Bug Summary

This is a continuation of potential issues that we have with reading SAC files, which first came up in [our forum](https://discourse.obspy.org/t/ppsd-plot-temporal-doesnt-work/1846/7) and was first looked at in #3387.

The issue is that SAC stores the sampling rate information as a 4-byte floating point representation of the sampling interval with units of seconds, which in turn can lead to floating point accuracy issues when reading that information and setting a sampling rate on a `Trace` assuming full accurate precision on the input data for the sampling rate.
The errors start out small of course, but can lead to significant errors on very long traces.

In fact, when reading SAC (converting the special `SACTrace` to a regular obspy `Trace`), there is some hidden rounding going on that seems to save us from harm in most cases, which also seems to be why this problem has not surfaced before.

In the original data example, the sample spacing is saved in the file as four bytes (`b'\x0b\xd7#='`), which gets read into a `float32` as `0.040000003` with the likely meaning of exactly 0.04 s, i.e. 25 Hz sampling rate. The sample spacing is off due to floating point accuracy by roughly 2.8 ns.
In this case, if we construct a trace from scratch and set the sampling rate to 25 Hz, save as SAC and read it again, we end up without inaccuracies for a combination of two reasons. The binary representation in the original file is slightly off, with `b'\n\xd7#='` the sampling spacing can be better represented with just a floating point error of roughly 0.9 ns. And then this remaining error seems to get rounded away [when we convert the float32 spacing interval to float64 sampling frequency](https://github.com/obspy/obspy/blob/dfb021350cb4e05f6baa76982c789352b02c3241/obspy/io/sac/util.py#L231C5-L231C64):

```python
stats['sampling_rate'] = np.float32(1.) / np.float32(delta)
```

My feeling is, when the SAC format was established, sample spacing was not considered to have accuracy below let's say maybe microseconds. And probably in SAC code some rounding is going on to avoid these floating point inaccuracies (I don't have a copy of the source code at hand right now).

What we could do is round the (inaccurate) sample spacing we read out from that 4-byte float to a certain decimal (e.g. round to microseconds) before using it to set the sampling rate on the trace at a higher accuracy. But that might bring other problems I might not think of right now. So I'd like to hear other opinions, especially from people that might have insight what SAC is doing to avoid this issue.

```python
stats['sampling_rate'] = 1.0 / round(np.float64(delta), 6)
```

@jkmacc-LANL do you have any input on this by chance?

Anybody know how SAC is handling this internally?

### Code to Reproduce

```python
# SAC file from original report on the forum starts with those 4 bytes encoding the sample spacing in the SAC file header
data = b'\x0b\xd7#='

# these get interpreted as a float32 as sample spacing in seconds
delta = np.frombuffer(data, np.float32)[0]

# internally for the Trace object we set the sampling rate like this
sampling_rate = np.float32(1.) / np.float32(delta)

# which leads to floating point accuracy hitting (e.g. when calculating the timing of a sample at the back of a very long Trace)
print(sampling_rate)     #  -> 24.999998

# potential solution.. add some rounding of the sampling interval (e.g. to integer microseconds)

sampling_rate = 1.0 / round(np.float64(delta), 6)
print(sampling_rate)     #  -> 25.0
```

### ObsPy Version?

1.4.0 / current master

### Operating System?

Debian bullseye

### Python Version?

3.10.5

### Installation Method?

developer installation / from source / git checkout

**Comment by filefolder** [comment]
I have noticed this problem quite a bit but never fully understood what was happening. 

Have been assuming that the sample rate in these instances has been _calculated_ rather than specified, so if a 40hz recording spans 24 hours, but is on occasion one sample off, then the sampling rate will be given as  `3455999/86400 = 39.99998842592593` in the header. I have actually seen 39.9999 a lot with older AU data that is hosted at IRIS/EarthScope but I don't have an example on hand, assuming it's even the same issue.

**Comment by jkmacc-LANL** [comment]
@megies First of all, thank you for such a well described issue.  It's clear that you've invested a lot of time and thought into it.

Do we know if the old implementation reproduces the issue? If not, I could look at how they avoided the problem.

**Comment by megies** [comment]
> Do we know if the old implementation reproduces the issue?

I just tried on ObsPy 0.10.3 which I believe is the last release pre io.sac-rewrite and it's the same. I think we should look in SAC source code or ask SAC maintainers about it, but I couldn't find SAC source code in my stuff and couldn't be asked to fill in that request form

**Comment by jkmacc-LANL** [comment]
I've dug around looking for SAC source code or descriptions of this and spoken with someone who knows it pretty well, but without success.  The closest thing I could find is [this line in `sac2mseed`](https://github.com/EarthScope/sac2mseed/blob/main/src/sac2mseed.c#L346), written by folks who have presumably had to deal with this issue.  Apparently (mini)SEED stores both a sample rate and a multiplier so that this type of thing can be avoided.  

Given that this issue is related to a bad combination of file format and datatype and not related to ObsPy, I guess we get to decide how to (or if) we handle it.  I'm open to a solution like yours/Earthscope's, if you think it best.  It might be just a quick fix in the `io.sac` submodule...

**Comment by megies** [comment]
Thanks for looking into it. That line you dug up is (pretty much?) exactly doing what I could think of as a fix above, basically rounding the float sample spacing to six digits, which implies that any data with a valid sampling interval with accuracy below microseconds would get invalidated but on the other hand making sure that other data will never suffer from single precision floating point accuracy issues in terms of sample spacing / sampling rate.

Still would be nice to confirm if SAC itself does something like this in the code, but I agree we should probably just go ahead and add this rounding. I feel like we can assume that the likelihood of valid sample spacings with accuracy below microseconds is quite slim.

**Comment by megies** [comment]
@chad-earthscope you happen to have come across this issue before? Don't wanna make you waste time researching this, just in case you have previous experience you can share.

**Comment by chad-earthscope** [comment]
It is not an issue I remember well, but it's a general one for long time series and accumulating small errors in rate. miniSEED usually isn't affected as much because each record represents a relatively short time series and the variation and non integer characteristics in rate and timing do not accumulate.  The rounding approach is decently pragmatic.  Unfortunately it also completes with the cases where the true sampling rate is actually very, very near a rounded value.

**Comment by megies** [comment]
Hmm yeah. I figure maybe we should round and issue a warning if rounding made a difference..
