### ISSUE TITLE
Order of traces within a Stream.plot() is incorrect

### ISSUE THREAD

**Issue by trac2github** [obspy/obspy#81]
Sort order used to be ''id, starttime, endtime'' - but this does not work anymore.

{{{

> > > from obspy.core import read
> > > st = read("http://svn.geophysik.uni-muenchen.de/obspy/examples/ArclinkRequest_340397.fseed")
> > > print st
> > > 3 Trace(s) in Stream:
> > > GE.APE..BHN | 2009-10-01T14:21:38.505000Z - 2009-10-01T14:22:08.555000Z | 20.0 Hz, 602 samples
> > > GE.APE..BHZ | 2009-10-01T14:21:34.445000Z - 2009-10-01T14:22:05.545000Z | 20.0 Hz, 623 samples
> > > GE.APE..BHE | 2009-10-01T14:21:50.675000Z - 2009-10-01T14:22:21.125000Z | 20.0 Hz, 610 samples
> > > st.plot()
> > > }}}

-> plot see attachment.

'''However''', sorting should be done outside of the plotting method - we got a Stream.sort() method for that. The plotting routine should use the order within the stream object.

**Comment by AntonBiryukovUofC** [comment]
Hello folks,

Could you please confirm that stream.plot() plots in the correct order (i.e. order that print(stream) indicates) ?
Does not seem to be the case for me :(

**Comment by krischer** [comment]
By default is does not plot in the same order as in the Stream object. The reason is that plotting might require some fairly extensive merging for multiple piece and component streams so that gaps/overlaps and what not are correctly plotted. It attempts to plot in a "sane" ZNE/ZRT/LQT no matter what the order within the Stream object which is also nice as components are always in the same place.

You can turn off all of that merging and reordering with `plot(automerge=False)` in which case it will just plot trace after trace in whatever order they appear.
