### ISSUE TITLE
Some TauP paths do not end at the requested location

### ISSUE THREAD

**Issue by QuLogic** [obspy/obspy#986]
Pulled this out of #959 for tracking purposes. Probably shouldn't hold up the release, though. @crotwell can comment here if he has any further input.

> I did find some other (a bit obscure) phases where it does not quite add up. The issue is identical in your Java version and our Python port. On the left is always the Python version, on the right the Java version.
![untitled](https://cloud.githubusercontent.com/assets/800487/6229800/abf51eb6-b6ba-11e4-8d3e-b43588f34e41.png)

**Comment by crotwell** [comment]
I believe I have fixed this in TauP (java) with commits 

https://github.com/crotwell/TauP/compare/98dc60ccb272f2bf4ec69a32b0e546d3c2a2cd4d...9b737bd9d11a0c6fdf758051b709ad3d4e7ee33c

Basic issue is that the path is very sensitive to ray parameter for very long phases like PKPPKP.  The linear interpolation does a reasonable job of getting close to the time, but when taup calculates the path, it uses the interpolated arrival's ray parameter and sends it back through the model. But if the ray parameter is slightly wrong due to the linear interpolation in the original calculation, and the path is long, then the errors accumulate and the output can be off by a couple of degrees. The new method does a refinement calculation shooting rays that helps to get a much more accurate ray parameter, and hence more accurate path. Some tradeoff in speed, so I might make this optional before the release.

Other little bug fixes and improvements in there as well.

**Comment by crotwell** [comment]
Also, prerelease of TauP with this fix in it is here:
http://www.seis.sc.edu/downloads/TauP/prerelease/TauP-2.3.0-SNAPSHOT.tgz

**Comment by QuLogic** [comment]
Thanks for the update @crotwell. We'll try and look into incorporating the changes soon.
